### ISSUE TITLE
Issue with database juggler / mongodb

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback-next#1049]
# Description/Steps to reproduce

I can retrieve all models 👍 

```
const models = await this.repository.find()
```

But when I want to filter, it doesn't work. Always empty list. 👎 

```
const venueModels = await this.repository.find({where: {foursquareId: '5952cf02829b0c59fa430f63'}})
```

But it works if I directly apply filter in mongodb: 👍 

```
db.getCollection('TestFoursquare').find({ foursquareId: '5952cf02829b0c59fa430f63' })
```

Also one more issue when I try findOne, may be related: 👎 

```
const model = await this.repository.findOne({where: { foursquareId: '5952cf02829b0c59fa430f63' }})
```

```
  loopback:connector:mongodb all TestFoursquare { where: { foursquareId: '5952cf02829b0c59fa430f63' },
  limit: 1,
  offset: 0,
  skip: 0 } null [] +8ms
  loopback:rest:error Unhandled error in GET /places/around: 500 TypeError: Cannot read property 'toObject' of null
    at UntappedFoursquareRepository.toEntity (/Users/alex/ProjectsAlex/droppy.shop/api.follow.beer/node_modules/@loopback/repository/dist/src/legacy-juggler-bridge.js:148:43)
    at UntappedFoursquareRepository.findOne (/Users/alex/ProjectsAlex/droppy.shop/api.follow.beer/node_modules/@loopback/repository/dist/src/legacy-juggler-bridge.js:102:21)
    at <anonymous> +0ms
```

**Comment by shimks** [comment]
Hi @cajoy! I wasn't able to reproduce the issue using our modified `todo` application using the `mongodb` connector. Is this still an issue for you? If it is, could you provide us with a reproduction sandbox?

**Comment by shimks** [comment]
@cajoy Please let us know if this is still an issue for you. If it isn't, this issue is slated for closure by the end of May.
