### ISSUE TITLE
`npm start` fails for newly created lb4 project

### ISSUE THREAD

**Issue by seanpk** [strongloop/loopback-next#1367]
## Description / Steps to reproduce / Feature proposal
Follow the [Getting started](http://loopback.io/doc/en/lb4/Getting-started.html) guide, get to the part where you run `npm start`.
Find out that you need to install two additional packages `base64-js` and `ieee754` for the command to execute successfully.

Ubuntu 18.04, node v10.2.1, npm 5.6.0.

## Current Behavior
After running `npm start` get an error that includes:
```
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'base64-js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
```
When you `npm i base64-js`, you'll get a similar error calling for `ieee754` that you can resolve by running `npm i ieee754`

## Expected Behavior
The project should execute as documented.

**Comment by raymondfeng** [comment]
Hi, I just tried by myself and everything works as expected. Can you post the complete stack trace for your error?

**Comment by davidmehren** [comment]
I have the same problem under Arch Linux with node 10.2.1 (npm v6.1.0).

If I try `npm start` right after creating a new project with `lb4` I get the following:
```
~/P/lb-4-test $ npm start

> lb4-test@1.0.0 start /home/david/Projekte/lb-4-test
> npm run build && node .


> lb4-test@1.0.0 build /home/david/Projekte/lb-4-test
> lb-tsc

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'base64-js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/david/Projekte/lb-4-test/node_modules/swagger-client/dist/index.js:7:11309)
    at t (/home/david/Projekte/lb-4-test/node_modules/swagger-client/dist/index.js:1:177)
    at Object.<anonymous> (/home/david/Projekte/lb-4-test/node_modules/swagger-client/dist/index.js:7:7)
    at Object.<anonymous> (/home/david/Projekte/lb-4-test/node_modules/swagger-client/dist/index.js:7:11111)
    at t (/home/david/Projekte/lb-4-test/node_modules/swagger-client/dist/index.js:1:177)
    at Object.<anonymous> (/home/david/Projekte/lb-4-test/node_modules/swagger-client/dist/index.js:1:48717)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lb4-test@1.0.0 start: `npm run build && node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lb4-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2018-05-27T15_13_05_103Z-debug.log

```

After `npm install base64-js ieee754` I can start the server, but accessing http://localhost:3000/ping crashes it with
```
Server is running at http://127.0.0.1:3000
Try http://127.0.0.1:3000/ping
/home/david/Projekte/lb-4-test/node_modules/@loopback/rest/dist/src/rest-server.js:423
            throw err;
            ^

Error: The key rest.sequence.actions.findRoute was not bound to any value.
    at Lb4TestApplication.getBinding (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/context.js:242:15)
    at RestServer.getBinding (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/context.js:238:33)
    at Context.getBinding (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/context.js:238:33)
    at Context.getValueOrPromise (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/context.js:276:30)
    at resolution_session_1.ResolutionSession.runWithInjection.s (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolver.js:108:24)
    at value_promise_1.tryWithFinally (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolution-session.js:89:53)
    at Object.tryWithFinally (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/value-promise.js:157:18)
    at Function.runWithInjection (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolution-session.js:89:32)
    at resolve (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolver.js:101:59)
    at value_promise_1.resolveList (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolver.js:169:16)
    at Object.resolveList (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/value-promise.js:130:32)
    at resolveInjectedArguments (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolver.js:153:28)
    at Object.instantiateClass (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolver.js:37:27)
    at Binding._getValue (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/binding.js:356:55)
    at resolution_session_1.ResolutionSession.runWithBinding.s (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/binding.js:219:90)
    at value_promise_1.tryWithFinally (/home/david/Projekte/lb-4-test/node_modules/@loopback/context/dist/src/resolution-session.js:69:53)
```

This also happens with node v8.11.2 (npm v5.6.0).

**Comment by raymondfeng** [comment]
Can you run `npm ls swagger-client` and post the result here?

**Comment by davidmehren** [comment]
```
$ npm ls swagger-client
lb4-test@1.0.0 /home/david/Projekte/lb-4-test
└─┬ @loopback/rest@4.0.0-alpha.26
  └─┬ @loopback/openapi-v2@4.0.0-alpha.11
    └─┬ @loopback/repository-json-schema@4.0.0-alpha.8
      └─┬ @loopback/repository@4.0.0-alpha.30
        └─┬ loopback-datasource-juggler@3.21.1
          └─┬ strong-globalize@3.3.0
            └─┬ g11n-pipeline@2.0.6
              └── swagger-client@3.8.5 
```

**Comment by raymondfeng** [comment]
It seems that `swagger-client@3.8.5` is completely broken. The problem can be reproduced as follows:

```
cd /tmp
npm i swagger-client@3.8.5
node
> require('swagger-client');
```

**Comment by raymondfeng** [comment]
https://github.com/swagger-api/swagger-js/issues/1326 is the culprit.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/swagger-api/swagger-js/pull/1328
