### ISSUE TITLE
Datasource name other than 'db' throws 500

### ISSUE THREAD

**Issue by jdumont0201** [strongloop/loopback-next#1566]
## Description
Minor issue: 
`lb4 datasource` accepts a datasource name at creation, but any name other than "_db_" will throw error 500 at request time.

## Steps to reproduce
Follow the TODO tutorial.
When creating datasource, set a different name than "db", eg _mydatabasename_. 

## Current Behavior

Query : http://127.0.0.1:3000/todos 

**Unhandled error in GET /todos: 500 Error: The key datasources.db was not bound to any value.**
    at PolitronApi.getBinding (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/context.js:216:15)
    at RestServer.getBinding (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/context.js:212:33)
    at RequestContext.getBinding (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/context.js:212:33)
    at RequestContext.getValueOrPromise (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/context.js:251:30)
    at resolution_session_1.ResolutionSession.runWithInjection.s (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolver.js:73:24)
    at value_promise_1.tryWithFinally (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolution-session.js:89:53)
    at Object.tryWithFinally (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/value-promise.js:162:18)
    at Function.runWithInjection (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolution-session.js:89:32)
    at resolve (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolver.js:66:59)
    at value_promise_1.resolveList (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolver.js:144:16)
    at Object.resolveList (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/value-promise.js:135:32)
    at resolveInjectedArguments (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolver.js:128:28)
    at Object.instantiateClass (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolver.js:37:27)
    at Binding._getValue (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/binding.js:355:55)
    at resolution_session_1.ResolutionSession.runWithBinding.s (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/binding.js:188:90)
    at value_promise_1.tryWithFinally (/home/jbmdu/dev/politron/politron-api/node_modules/@loopback/context/dist8/src/resolution-session.js:69:53)

## Expected Behavior
Any db name should be allowed.
The key should be datasources.mydatabasename instead of datasources.db ?

## Workaround
Name your datasource _db_

**Comment by dhmlau** [comment]
Yes. The key name should be `datasources.mydatabasename` instead of `datasources.db`.   The current instruction in the tutorial does assume the datasource name to be `db`. 

We've updated the instructions (https://github.com/strongloop/loopback.io/tree/gh-pages/pages/en/lb4/todo-tutorial-*.md).  However, for some reason, it didn't get refreshed on loopback.io.  Looking into the issue now.  Thanks.

**Comment by dhmlau** [comment]
Moving to `In Progress`, since @shimks has a PR up.
