### ISSUE TITLE
Cannot create a kv-memory datasource using `lb4 datasource`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-next#1697]
## Description / Steps to reproduce / Feature proposal

Create an LB4 app, e.g. via `lb4 app`.

Try to create a datasource backed by `kv-memory` connector by running `lb4 datasource`.

## Current Behavior

The process crashes.

```
$ lb4 datasource
? Datasource name: keyvalue
? Select the connector for keyvalue: In-memory key-value connector (supported by StrongLoop)
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at DataSourceGenerator.promptConnectorConfig (/Users/bajtos/src/loopback/next/packages/cli/generators/datasource/index.js:159:12)
    at Object.<anonymous> (/Users/bajtos/src/loopback/next/packages/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/bajtos/src/loopback/next/packages/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/bajtos/src/loopback/next/packages/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/bajtos/src/loopback/next/packages/cli/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/bajtos/src/loopback/next/packages/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

## Expected Behavior

The datasource is created.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
When I select the `kv-redis` connector, everything works as expected.
