### ISSUE TITLE
Error: Cannot find module '/home/aleksei/LoopBack4/getting-started/dist10'

### ISSUE THREAD

**Issue by aleksei-timofeyev** [strongloop/loopback-next#1714]
## Description / Steps to reproduce / Feature proposal
Scaffold a new app
lb4 app
cd getting-started
npm start

Possibly related to #1557

## Current Behavior
After scaffolding a new app in lb4 version 0.22.10 and run npm start it complains with the following message:
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/aleksei/LoopBack4/getting-started/dist10'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.loadDist (/home/aleksei/LoopBack4/getting-started/node_modules/@loopback/dist-util/index.js:36:10)
    at Object.<anonymous> (/home/aleksei/LoopBack4/getting-started/index.js:1:114)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getting-started@1.0.0 start: `npm run build && node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the getting-started@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aleksei/.npm/_logs/2018-09-15T13_39_22_695Z-debug.log
```
node --version
v10.10.0

npm --version
6.4.1

## Expected Behavior
The app should start without any problems.

## Temporary workaround 
Make the symlink with name dist10 pointing to dist.

**Comment by raymondfeng** [comment]
npm run build should fix it. Did u create the app using lb4 cli?

**Comment by aleksei-timofeyev** [comment]
> Did u create the app using lb4 cli?
Yes, I did.
npm run build creates dist folder:
```
 npm run build

> getting-started@1.0.0 build /home/aleksei/LoopBack4/getting-started
> tsc --outDir dist --target es2017
```

**Comment by raymondfeng** [comment]
I see what's going now. You probably disabled `Enable loopback build`. There is a problem in the generated package.json.

**Comment by raymondfeng** [comment]
```json
{
  "scripts": {
    "build": "tsc --outDir dist --target es2017",
    "build:all-dist": "npm run build",
    "build:watch": "tsc --outDir dist --target es2017 --watch",
    ...
  }
}
```

**Comment by raymondfeng** [comment]
To be fixed by #1715

**Comment by aleksei-timofeyev** [comment]
> What's in your package.json?

```
~/LoopBack4/getting-started $ cat package.json
{
  "name": "getting-started",
  "version": "1.0.0",
  "description": "getting-started-description",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8.9"
  },
  "scripts": {
    "build": "tsc --outDir dist --target es2017",
    "build:all-dist": "npm run build",
    "build:watch": "tsc --outDir dist --target es2017 --watch",
    "clean": "rm -rf dist",
    "pretest": "npm run clean && npm run build",
    "test": "mocha dist/test",
    "test:dev": "mocha dist/test/**/*.js",
    "start": "npm run build && node .",
    "prepare": "npm run build"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "src"
  ],
...
```

> Did you follow http://v4.loopback.io/getting-started.html?
> 
> What's your `lb4` version? Use `lb4 --version` to check.

Yes. @loopback/cli version: 0.22.10

> I see what's going now. You probably disabled `Enable loopback build`. There is a problem in the generated package.json.

All features are enabled except mocha.

**Comment by raymondfeng** [comment]
Please try @loopback/cli@0.22.11: `npm i -g @loopback/cli`.

**Comment by aleksei-timofeyev** [comment]
@raymondfeng It's working now. Thanks!
