### ISSUE TITLE
Problem to post model with related array

### ISSUE THREAD

**Issue by ericalves** [strongloop/loopback-next#1813]
Hi guys!

I am trying persist (insert) a model with an array with your child models.

I have a model Store and its has hasMany relation with Store_Shift.. When i persist a json object like that:

`{
  "id_store": 0,
  "trade_name": "Test Store",
  "shifts": [
    {
      "id_store_shift": 0,
      "id_store": 0,
      "desc_store_shift": "day",
      "starting_time": "08:00",
      "use_service_charge": "N"
    }
  ]
}`

i receive this error:

> Unhandled error in POST /store: 500 TypeError: Function has non-object prototype 'undefined' in instanceof check                                                                       
    at Function.[Symbol.hasInstance] (<anonymous>)                                                                                                                                     
    at D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\list.js:71:28                                                                         
    at Array.forEach (<anonymous>)                                                                                                                                                     
    at new List (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\list.js:70:9)                                                               
    at List (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\list.js:17:12)                                                                  
    at Store.set [as shifts] (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\model-builder.js:594:43)                                       
    at Store.ModelBaseClass._initProperties (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\model.js:202:17)                                
    at Store.ModelBaseClass (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\model.js:60:8)                                                  
    at new Store (eval at createModelClassCtor (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\model-builder.js:671:21), <anonymous>:12:24) 
    at Function.DataAccessObject.create (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\dao.js:361:13)                                      
    at DsMainDataSource.onConnected (D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\datasource.js:2524:14)                                  
    at Object.onceWrapper (events.js:313:30)                                                                                                                                           
    at emitNone (events.js:106:13)                                                                                                                                                     
    at DsMainDataSource.emit (events.js:208:7)                                                                                                                                         
    at D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\datasource.js:323:12                                                                  
    at D:\Desenvolvimento\PDV\Fontes\api-clientsync\node_modules\loopback-datasource-juggler\lib\connectors\memory.js:145:15                                                           

if i post only store structure (withou shifts), its works.

in explorer example value has shifts.

![image](https://user-images.githubusercontent.com/2515487/46552410-009f3300-c8b1-11e8-92eb-b373e8dd7d49.png)

im using node v8.12.0.

i follow the todolist example to add relations.

i put my source here [github](https://github.com/ericalves/test-lb4)

**Comment by ericalves** [comment]
Hi.

I have one more problem.. im testing my structure then i insert some stores and after tried insert one store_shift but i have this error:

I has this STORES:
![image](https://user-images.githubusercontent.com/2515487/46556312-a3a97a00-c8bc-11e8-939d-907fe90f5388.png)

and tried insert this store_shift and put in ID (url parameter) 1 (one). but i received this error:
![image](https://user-images.githubusercontent.com/2515487/46556359-cb004700-c8bc-11e8-99a5-28a15b8f7922.png)

my post:
![image](https://user-images.githubusercontent.com/2515487/46556433-01d65d00-c8bd-11e8-9759-92800d1261a7.png)

my controller:
```
export class StoreStoreShiftsController {
  constructor(
    @repository(StoreRepository)
    protected storeRepository: StoreRepository,
  ) { }

  @post('/store/{id}/shifts')
  async createOrder(
    @param.path.number('id') id_store: typeof Store.prototype.id_store,
    @requestBody() orderData: Store_shift,
  ): Promise<Store_shift> {
    console.log('here >', orderData)
    // orderData.id_store = id_store
    return await this.storeRepository.shifts(id_store).create(orderData);
  }
}
```

**Comment by raymondfeng** [comment]
@ericalves I can reproduce the problem now. The `@hasMany` decorator uses a type resolver `@hasMany(() => Store_shift)` but our 3.x juggler does not understand that. We'll come up a fix soon.

**Comment by ericalves** [comment]
Thanks @raymondfeng ! i think this issue can be closed. :D
