### ISSUE TITLE
Loopback 4 belongsTo relation got error

### ISSUE THREAD

**Issue by samhoamt** [strongloop/loopback-next#2007]
## Description
Hi, I'm working on the belongsTo relation to two models (Restaurant, Cuisine). I follow the documentation exactly. After setting up, I use the LoopBack API Explorer to do the GET request and POST request to Restaurant (source Model) and I got the following response body:

`{
  "error": {
    "statusCode": 500,
    "message": "Internal Server Error"
  }
}`

Console error:
`
Unhandled error in GET /restaurants: 500 TypeError: Cannot read property 'target' of undefined
    at resolveBelongsToMetadata (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/repository/dist/src/relations/belongs-to/belongs-to-accessor.js:41:54)
    at Object.createBelongsToAccessor (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/repository/dist/src/relations/belongs-to/belongs-to-accessor.js:18:18)
    at RestaurantRepository._createBelongsToAccessorFor (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/repository/dist/src/repositories/legacy-juggler-bridge.js:134:28)
    at new RestaurantRepository (/Users/samhoe/Documents/hornbill-food/api/dist/src/repositories/restaurant.repository.js:22:29)
    at value_promise_1.transformValueOrPromise.args (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/resolver.js:44:16)
    at Object.transformValueOrPromise (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/value-promise.js:231:16)
    at Object.instantiateClass (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/resolver.js:39:34)
    at Binding._getValue (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/binding.js:355:55)
    at resolution_session_1.ResolutionSession.runWithBinding.s (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/binding.js:188:90)
    at value_promise_1.tryWithFinally (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/resolution-session.js:69:53)
    at Object.tryWithFinally (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/value-promise.js:162:18)
    at Function.runWithBinding (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/resolution-session.js:69:32)
    at Binding.getValue (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/binding.js:188:65)
    at RequestContext.getValueOrPromise (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/context.js:254:36)
    at resolution_session_1.ResolutionSession.runWithInjection.s (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/resolver.js:73:24)
    at value_promise_1.tryWithFinally (/Users/samhoe/Documents/hornbill-food/api/node_modules/@loopback/context/dist/src/resolution-session.js:89:53)
`

I also checked belongs-to-accessor.js and found that **belongsToMetadata** param in **createBelongsToAccessor(line 17)** function is **undefined**.

**Comment by samhoamt** [comment]
The issue solved after updated modules.

**Comment by JacobBrauchler** [comment]
@samhoamt what modules did you have to update?

**Comment by ghtech** [comment]
Hi I am getting same error any luck to resolve this problem. @samhoamt what modules did you have to update?

**Comment by samhoamt** [comment]
Sorry I can't remember exactly what module. I think is loopback-cli.

**Comment by xfter16** [comment]
Hi I am getting same error any luck to resolve this problem.

**Comment by bajtos** [comment]
I am afraid the comments above are not very helpful. For anybody encountering this issue: please create a small application we can use to reproduce the problem locally (see our [bug reporting instructions](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs)), open a new issue and add a reference to `#2007` in the description of that new issue.
