### ISSUE TITLE
[CLI] Cannot update @types/node version on a generated project

### ISSUE THREAD

**Issue by leon19** [strongloop/loopback-next#2028]
## Description / Steps to reproduce / Feature proposal

When setting `@types/node` version to `*` on an loopback cli generated project, the cli cannot longer be used to generate models/controllers/repositories, etc.

```
npm install -g @loopback/cli@1.1.0
lp4 app
cd [app-name]

# update package.json devDependency "@types/node" to "*"

lb4 model
```

## Current Behavior

The CLI throws an error and the generator is not run

```txt
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid Version: [object Object]
    at new SemVer (/home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:296:11)
    at compare (/home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:585:10)
    at lt (/home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:619:10)
    at cmp (/home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:660:21)
    at Comparator.intersects (/home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:759:5)
    at /home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:874:33
    at Array.every (<anonymous>)
    at /home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:873:33
    at Array.some (<anonymous>)
    at /home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/semver/semver.js:872:24
Emitted 'error' event at:
    at Immediate.setImmediate (/home/user/.nvs/node/10.13.0/x64/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

## Expected Behavior

No error at all, or throw a more descriptive error indicating the dependencies should not be altered in the cli generated project

I believe the problem resides in the following piece code

https://github.com/strongloop/loopback-next/blob/b7be5c9612d8aff7beacbb88f9cf4936060c1cc5/packages/cli/lib/base-generator.js#L344-L349

**Comment by raymondfeng** [comment]
It seems to be a bug in `semver`. For example:

```
semver.intersects('*', '^10.11.2')
TypeError: Invalid Version: [object Object]
```

**Comment by raymondfeng** [comment]
See https://github.com/npm/node-semver/issues/236

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-next/pull/2042
