### ISSUE TITLE
main function getting called two times

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next#2191]
## Description / Steps to reproduce / Feature proposal
In `@loopback/example-rpc-server`, main function is calling two times which causing below error for port binding of application start call.

## Current Behavior

```
Server is running on port 3000
Cannot start the application. { Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (C:\workspace\samples\banjara.tours\backend-services\content-publisher\node_modules\express\lib\application.js:618:24)
    at RPCServer.start (C:\workspace\samples\banjara.tours\backend-services\content-publisher\dist\src\rpc.server.js:34:43)
    at _forEachServer.s (C:\workspace\samples\banjara.tours\backend-services\content-publisher\node_modules\@loopback\core\dist\src\application.js:127:42)
    at Promise.all.bindings.map (C:\workspace\samples\banjara.tours\backend-services\content-publisher\node_modules\@loopback\core\dist\src\application.js:149:26)
    at <anonymous>
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000}
```

**Comment by hacksparrow** [comment]
For anyone who's not sure what's happening: `main()` is first called in `index.ts`, and the second time in `index.js`.
