### ISSUE TITLE
How to specify database specific property settings when using relation?

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#2345]
## Description / Steps to reproduce / Feature proposal

How to specify the postgres dataType when using belongsTo-Relation?

Example:
```javascript
@model()
export class ModelA extends Entity {

  @property({
    id: true,
    defaultFn: 'uuidv4',
    mysql: { dataType: 'varchar', dataLength: 36 },
    postgresql: { dataType: 'uuid', columnName: 'id', nullable: 'YES' },
  })
  id?: string;

  @belongsTo(() => ModelB)
  @property({
    required: true,
    mysql: { dataType: 'varchar', dataLength: 36 },
    postgresql: { dataType: 'uuid', columnName: 'modelb_id', nullable: 'NO' },
  })
  modelbId: UUID;
}
```

## Current Behavior

```
Error: Decorator cannot be applied more than once on ModelA.prototype.modelbId
    at PropertyDecoratorFactory.mergeWithOwn (./node_modules/@loopback/metadata/dist/src/decorator-factory.js:321:19)
    at PropertyDecoratorFactory.decorate (./node_modules/@loopback/metadata/dist/src/decorator-factory.js:219:25)
    at ./node_modules/@loopback/metadata/dist/src/decorator-factory.js:327:47
    at ./node_modules/@loopback/repository/dist/src/relations/belongs-to/belongs-to.decorator.js:23:45
    at DecorateProperty (./node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (./node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (./dist/src/models/modela.model.js:4:92)
    at Object.<anonymous> (./dist/src/models/modela.model.js:33:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./dist/src/models/index.js:86:10)
```

## Expected Behavior

I need a way to specify dataType for postgres for fields which a marked with belongsTo decorator. I think the implicit definition of property by belongsTo should merge with existing property decorator?

**Comment by derdeka** [comment]
related to #2256
