### ISSUE TITLE
[CLI] How to use custom schema with postgres connector in loopback 4

### ISSUE THREAD

**Issue by MrJim-06** [strongloop/loopback-next#2388]
**I'm use this code to use custom schema in todo.model.ts file**
```typescript
import { Entity, model, property } from '@loopback/repository';

@model({ options: { postgresql: { schema: 'testschema' } } })
export class Todo extends Entity {
  @property({
    type: 'number',
    id: true,
  })
  id?: number;

  @property({
    type: 'string',
    required: true,
  })
  title: string;

  @property({
    type: 'string',
    required: true,
  })
  author: string;

  @property({
    type: 'string',
    required: true,
  })
  description: string;

  @property({
    type: 'boolean',
  })
  isComplete?: boolean;


  constructor(data?: Partial<Todo>) {
    super(data);
  }
}

```
**this is error**

```
Unhandled error in GET /todos: 500 error: relation "public.todo" does not exist
    at Connection.parseE (C:\Users\develop\Desktop\test-project\loopback-postgres\node_modules\pg\lib\connection.js:555:11)
    at Connection.parseMessage (C:\Users\develop\Desktop\test-project\loopback-postgres\node_modules\pg\lib\connection.js:380:19)
    at Socket.<anonymous> (C:\Users\develop\Desktop\test-project\loopback-postgres\node_modules\pg\lib\connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by dhmlau** [comment]
@MrJim-06 , please use `settings` instead of `options`.  
For details, see https://github.com/strongloop/loopback-next/issues/2134#issuecomment-445494970. 
Let me see how we should update the documentation.  Thanks!

**Comment by dhmlau** [comment]
If this resolves your question, please let me know and I can close this ticket. 
#2134 can be used to improve the docs.

**Comment by MrJim-06** [comment]
@dhmlau yes that's work thank you.

**Comment by dhmlau** [comment]
Closing it as resolved.
