### ISSUE TITLE
Please help me. I'm very ordinary on loopback 4. Error: The key rest.sequence.actions.findRoute was not bound to any value

### ISSUE THREAD

**Issue by ululajib** [strongloop/loopback-next#2402]
### Error: The key rest.sequence.actions.findRoute was not bound to any value.

when I run npm start and run " http://127.0.0.1:3001 " in the browser.

and I am now confused what to do. Please help me

## Error

 get-started-loop npm start

> get-started-loop@1.0.0 start /home/ulul/jm-blank/get-started-loop
> npm run build && node .

> get-started-loop@1.0.0 build /home/ulul/jm-blank/get-started-loop
> lb-tsc

Server is running at http://127.0.0.1:3001
Try http://127.0.0.1:3001/ping
/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/rest/dist/src/rest-server.js:423
            throw err;
            ^

Error: The key rest.sequence.actions.findRoute was not bound to any value.
    at GetStartedLoopApplication.getBinding (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/context.js:242:15)
    at RestServer.getBinding (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/context.js:238:33)
    at Context.getBinding (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/context.js:238:33)
    at Context.getValueOrPromise (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/context.js:276:30)
    at resolution_session_1.ResolutionSession.runWithInjection.s (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolver.js:108:24)
    at value_promise_1.tryWithFinally (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolution-session.js:89:53)
    at Object.tryWithFinally (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/value-promise.js:157:18)
    at Function.runWithInjection (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolution-session.js:89:32)
    at resolve (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolver.js:101:59)
    at value_promise_1.resolveList (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolver.js:169:16)
    at Object.resolveList (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/value-promise.js:130:32)
    at resolveInjectedArguments (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolver.js:153:28)
    at Object.instantiateClass (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolver.js:37:27)
    at Binding._getValue (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/binding.js:356:55)
    at resolution_session_1.ResolutionSession.runWithBinding.s (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/binding.js:219:90)
    at value_promise_1.tryWithFinally (/home/ulul/jm-blank/get-started-loop/node_modules/@loopback/context/dist/src/resolution-session.js:69:53)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-started-loop@1.0.0 start: `npm run build && node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get-started-loop@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ulul/.npm/_logs/2019-02-15T03_13_31_493Z-debug.log
➜  get-started-loop

**Comment by ululajib** [comment]
@dhmlau 
I just installed it and it keeps running npm start, and I immediately got the error

**Comment by dhmlau** [comment]
Let's make sure we have the right enviornment, and I have a few questions:
- which version of Node.js are you running?  It needs to be 8.9+
- which OS are you running on? 
- by default, the REST server is running on port 3000.  Did you add/modify the server?

One way to isolate whether it's your app's issue is to install and run the todo example.  Please follow the following steps to see if you're still running into the same issue:
1. install LB4 cli (latest is `@loopback/cli@1.6.0`)
```
npm i -g @loopback/cli
```

2. Run `lb4 example todo` to download the todo example
3. Start the app `npm start`

Hope it helps.

**Comment by dhmlau** [comment]
@ululajib , does installing the latest version of `loopback-next` modules help?

**Comment by dhmlau** [comment]
@ululajib , any updates?

**Comment by ululajib** [comment]
forgive me, I can only reply now. yeah after I update everything runs
perfectly. thank you and apologize me.

Pada tanggal Sel, 19 Mar 2019 pukul 09.37 Diana Lau <
notifications@github.com> menulis:
