### ISSUE TITLE
npm test fails when external soap service is not available

### ISSUE THREAD

**Issue by derdeka** [strongloop/loopback-next#2455]
## Description / Steps to reproduce / Feature proposal

- checkout loopback-next
- run "npm test"
- if external soap service is not available (service down?) - the test run fails

## Current Behavior

getting ETIMEDOUT errors:

```
Connection fails: Error: connect ETIMEDOUT 159.89.39.190:80
It will be retried for the next request.
Connection fails: Error: connect ETIMEDOUT 159.89.39.190:80 actions, concurrency 8
It will be retried for the next request.
....[                  ] - prepare: sill lifecycle No script for "prepare" in "@loopback/sandbox-app", continuing
......                ] - prepare: sill lifecycle No script for "prepare" in "@loopback/sandbox-app", continuing

  1889 passing (5m)
  3 pending
  14 failing

  1) Application
       rejects division by zero with 412 error:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  2) Application
       divides two numbers:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  3) Application
       adds two numbers:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  4) Application
       multiplies two numbers:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  5) Application
       subtracts two numbers:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  6) Application
       "after all" hook for "subtracts two numbers":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\tmp\loopback-next-derdeka\examples\soap-calculator\dist\__tests__\acceptance\application.acceptance.js)


  7) CalculatorService
       "before all" hook: givenACalculatorService for "adds two numbers":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\tmp\loopback-next-derdeka\examples\soap-calculator\dist\__tests__\integration\services\calculator.service.integration.js)


  8) app-generator (SLOW)
       "before all" hook: install dependencies:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  9) app-generator (SLOW)
       "after all" hook:
     Uncaught Error: connect ETIMEDOUT 159.89.39.190:80
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  10) cli
       lists available commands:
     TypeError: Cannot read property 'call' of undefined


  11) cli
       lists versions:
     TypeError: Cannot read property 'call' of undefined


  12) cli
       lists versions:
     TypeError: Cannot read property 'call' of undefined


  13) app-generator (SLOW)
       passes `npm test` for the generated project:
     TypeError: Cannot read property 'call' of undefined


  14) app-generator with --format
       generates all the proper files:

      AssertionError [ERR_ASSERTION]: src/application.ts, no such file or directory
      + expected - actual

      -false
      +true

      at convertArgs.forEach.file (packages\cli\node_modules\yeoman-assert\index.js:56:12)
      at Array.forEach (<anonymous>)
      at Function.assert.file (packages\cli\node_modules\yeoman-assert\index.js:54:26)
      at Context.it (packages\cli\test\integration\generators\app.integration.js:154:12)




=== ATTENTION - INVALID USAGE OF CONSOLE LOGS DETECTED ===

Connection fails: Error: connect ETIMEDOUT 159.89.39.190:80
    at msg (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\globalize.ts:285:29)
    at packMessage (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\globalize.ts:260:18)
    at Object.rfc5424 (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\globalize.ts:281:10)
    at StrongGlobalize.error (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\strong-globalize.ts:228:22)
    at CalculatorDataSource.postInit (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\loopback-datasource-juggler\lib\datasource.js:479:13)
    at C:\tmp\loopback-next-derdeka\examples\soap-calculator\node_modules\loopback-connector-soap\lib\soap-connector.js:153:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


Connection fails: Error: connect ETIMEDOUT 159.89.39.190:80
    at msg (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\globalize.ts:285:29)
    at packMessage (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\globalize.ts:260:18)
    at Object.rfc5424 (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\globalize.ts:281:10)
    at StrongGlobalize.error (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\strong-globalize\src\strong-globalize.ts:228:22)
    at CalculatorDataSource.postInit (C:\tmp\loopback-next-derdeka\packages\repository\node_modules\loopback-datasource-juggler\lib\datasource.js:479:13)
    at C:\tmp\loopback-next-derdeka\examples\soap-calculator\node_modules\loopback-connector-soap\lib\soap-connector.js:153:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


npm ERR! code ELIFECYCLE
npm ERR! errno 14
npm ERR! loopback-next@0.1.0 mocha: `node packages/build/bin/run-mocha "packages/*/dist/__tests__/**/*.js" "examples/*/dist/__tests__/**/*.js" "packages/cli/test/**/*.js" "packages/build/test/*/*.js"`
npm ERR! Exit status 14
```

## Expected Behavior

tests should not depend on external services or external service should be always available

**Comment by dhmlau** [comment]
@derdeka, thanks for reporting this.  We're aware of this and working on a resolution.  @raymondfeng created some soap services that can be run in a docker container (see #2444), the next step is to hook it up with CI and we will then no longer need to rely on external services.  

If you're ok, I'd like to close this ticket as the duplicate of #2444. Thanks.

**Comment by derdeka** [comment]
Duplicate of #2444
