### ISSUE TITLE
500 TypeError: Cannot read property 'target' of undefined - Loopback 4

### ISSUE THREAD

**Issue by DilupaSampath** [strongloop/loopback-next#2506]
I'm getting this issue. Any one know what is the problem.

Unhandled error in POST /users/5c7779643732ee36390b783b/sale-store: 500 TypeError: Cannot read property 'target' of undefined
    at resolveHasManyMetadata (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/repository/dist/relations/has-many/has-many-repository.factory.js:43:54)
    at Object.createHasManyRepositoryFactory (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/repository/dist/relations/has-many/has-many-repository.factory.js:27:18)
    at UserRepository.createHasManyRepositoryFactoryFor (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/repository/dist/repositories/legacy-juggler-bridge.js:142:28)
    at new UserRepository (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/dist/repositories/user.repository.js:23:33)
    at value_promise_1.transformValueOrPromise.args (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/resolver.js:44:16)
    at Object.transformValueOrPromise (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/value-promise.js:231:16)
    at Object.instantiateClass (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/resolver.js:39:34)
    at Binding._getValue (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/binding.js:356:55)
    at resolution_session_1.ResolutionSession.runWithBinding.s (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/binding.js:189:90)
    at value_promise_1.tryWithFinally (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/resolution-session.js:69:53)
    at Object.tryWithFinally (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/value-promise.js:162:18)
    at Function.runWithBinding (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/resolution-session.js:69:32)
    at Binding.getValue (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/binding.js:189:65)
    at RequestContext.getValueOrPromise (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/context.js:531:36)
    at resolution_session_1.ResolutionSession.runWithInjection.s (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/resolver.js:73:24)
    at value_promise_1.tryWithFinally (/home/dilupa/Speralabs/sterling_Vehicle_project/backEnd/lb4/original/sterling-aftercare-system-api/node_modules/@loopback/context/dist/resolution-session.js:89:53)

-- user.repository.ts --
import {
  DefaultCrudRepository,
  repository,
  HasManyRepositoryFactory,
} from '@loopback/repository';
import {User, SaleStore} from '../models';
import {DbDataSource} from '../datasources';
import {inject, Getter} from '@loopback/core';
import {SaleStoreRepository} from './sale-store.repository';

export class UserRepository extends DefaultCrudRepository<
  User,
  typeof User.prototype._id
> {
  public readonly sale_stores: HasManyRepositoryFactory<
    SaleStore,
    typeof User.prototype._id
  >;
  constructor(
    @inject('datasources.Db') dataSource: DbDataSource,
    @repository.getter(SaleStoreRepository)
    saleRepositoryGetter: Getter<SaleStoreRepository>,
  ) {
    super(User, dataSource);
    this.sale_stores = this.createHasManyRepositoryFactoryFor(
      'sale_stores',
      saleRepositoryGetter,
    );
  }
}

--user.model.ts--

const jwt = require('jsonwebtoken');

import {Entity, model, property, hasMany} from '@loopback/repository';
import {Vehicle} from './vehicle.model';
import {SaleStore} from './sale-store.model';

@model()
export class User extends Entity {
  @property({
    type: 'string',
    id: true,
  })
  _id?: string;

  @property({
    type: 'string',
    required: true,
  })
  userName: string;

  @property({
    type: 'string',
    required: true,
  })
  email: string;

  @property({
    type: 'string',
    required: true,
  })
  password: string;

  @property({
    type: 'string',
    required: true,
  })
  lastName: string;

  @property({
    type: 'string',
    required: false,
  })
  role: string;

  @property({
    type: 'string',
    required: false,
  })
  status: string;

  //relations
  @hasMany(() => SaleStore, {keyTo: 'userId'})
  salse?: SaleStore[];

  constructor(data?: Partial<User>) {
    super(data);
  }
  generateAuthToken() {
    const token = jwt.sign(
      {_id: this._id, username: this.userName, email: this.email},
      'TheVerySecurePrivateKey',
    );
    return token;
  }
}
--sale-store.model.ts--

import {Entity, model, property} from '@loopback/repository';

@model()
export class SaleStore extends Entity {
  @property({
    type: 'string',
    id: true,
    required: false,
  })
  _id: string;

  @property({
    type: 'string',
  })
  name?: string;

  @property({
    type: 'string',
  })
  address?: string;

  @property()
  userId?: string;

  constructor(data?: Partial<SaleStore>) {
    super(data);
  }
}
--user.controller.ts--

  @post('/users/{id}/sale-store')
  async addSaleStore(
    @param.path.string('id') id: string,
    @requestBody() saleStore: SaleStore,
  ) {
    console.log(id);
    return await this.userRepository.sale_stores(id).create(saleStore);
  }

**Comment by nmkataoka** [comment]
That error usually means your foreign property names in your model and repository files don't match up. Things like passing in the actual classes instead of the class name as a string to @repository.getter, "salse" instead of "sales_store" as the model property, and other typos cause that error. I think if you follow the format in [https://loopback.io/doc/en/lb4/Relations.html](https://loopback.io/doc/en/lb4/Relations.html) very closely the error should go away.

**Comment by dhmlau** [comment]
Thanks @nmkataoka. 
@DilupaSampath , were you able to resolve your problem based on the suggestion from @nmkataoka?

**Comment by DilupaSampath** [comment]
Yes i resolved my problem. thanks @nmkataoka.

**Comment by VigneshMeem** [comment]
I had belongs to relation previously to one of the model,  but I removed it in the model file not in the model's repository , Thanks it solved the problem
