### ISSUE TITLE
Error: Cannot find module 'yeoman-environment'

### ISSUE THREAD

**Issue by jippy89** [strongloop/loopback-next#2638]
## Description / Steps to reproduce / Feature proposal
`pnpm i -g @loopback/cli`

## Current Behavior
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/jippy98/.nvm/versions/node/v10.15.3/pnpm-global/2/node_modules/.registry.npmjs.org/@loopback/cli/1.8.4/node_modules/@loopback/cli/lib/cli.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

## Expected Behavior
Well, able to use it normally. This happens right after I installed it.

**Operating system**
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.4
Codename:	Illyria

**Node, NPM, PNPM version:**  
Node: v10.15.3
NPM: 6.4.1
PNPM: 3.0.1

**Comment by jippy89** [comment]
**Little Background**  
At first I thought that there's just an interruption during the download, however it turns out it keeps giving me those error, which I had no idea what it was. But I managed to google it and found this issue [here] (https://github.com/yeoman/yeoman/issues/1569), however upon re-installing, everything including `node`, `npm`, and `nvm`, I still had the same trouble!

I don't have any problem with other installation via `pnpm`.

**Comment by jippy89** [comment]
Sorry, accidentally clicked on **Close and Comment**

**Comment by jippy89** [comment]
Nevermind, it seems that the error just like what it said..  
I solve this by going to the `package.json` in the `../@loopback/cli/` and simply do `pnpm install`
