### ISSUE TITLE
Type/Interface used with request body validation is ignored

### ISSUE THREAD

**Issue by frodoe7** [strongloop/loopback-next#2641]
## Description / Steps to reproduce / Feature proposal
Given the following interface defined inside a controller:

```js
interface idAndAge {
 id : string,
 age : number
}
```

and here is the endpoint definition:

```js
@put('/tests')
  async replaceById(
    @requestBody() test: idAndAge,// <--to validate the input
  ): Promise<void> {
    await this.testRepository.updateAll(test,{id : test.id});
  }
```

When this endpoint receives the following input for example (which has properties not defined in the interface):

```json
{ anyKey: anyValue }
````

it accept it and ignore the validation

it should not allow the below values - because they are not included/against our interface idAndAge

```json
{ anyKey: anyValue }
````

please check [this repo](https://github.com/frodoe7/LB4RequestbodyValidation) , if you'd like to test the issue

**Comment by shadyanwar** [comment]
I am guessing this could be related to https://github.com/strongloop/loopback-next/issues/1179 and https://github.com/strongloop/loopback-next/issues/2082

**Comment by bajtos** [comment]
I am afraid TypeScript does not capture information about interfaces at runtime. Interfaces exist at compile time only.

You have two options:
- Describe your data type as a class, use `@model` and `@property` decorators.

    ```ts
    @model()
    class idAndAge {
      @property()
       id : string,
      
      @property()
      age : number
    }
    ```

- Provide an explicit schema for your request body argument.

    ```ts
    class MyController {
      // ...
      @put('/tests')
      async replaceById(
        @requestBody({
          content: {
            'application/json': {
              schema: {
                 // your OpenAPI schema goes here
              }
            },
          },
        })
        test: idAndAge,// <--to validate the input
      ): Promise<void> {
        await this.testRepository.updateAll(test,{id : test.id});
      }
    }
    ```

**Comment by frodoe7** [comment]
@bajtos 

Thank you for the quick response.

I have tried the first option. Unfortunately, it gives the following error:
`
Unhandled error in PUT /tests: 500 Error: The key 'repositories.TestRepository' is not bound to any value in context 0c7f5a30-4fd2-11e9-8580-
2faabf6cb00d
    at AyApplication.getBinding (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/context.js:503:15)
    at RestServer.getBinding (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/context.js:499:33)
    at RequestContext.getBinding (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/context.js:499:33)
    at RequestContext.getValueOrPromise (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/context.js:5
38:30)
    at resolution_session_1.ResolutionSession.runWithInjection.s (../LB4RequestbodyValidation/node_modules/@loopback/
context/dist/resolver.js:103:24)
    at value_promise_1.tryWithFinally (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolution-session.js:89:53)
    at Object.tryWithFinally (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/value-promise.js:158:18)
    at Function.runWithInjection (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolution-session.js:89:32)
    at resolve (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolver.js:94:59)
    at value_promise_1.resolveList (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolver.js:175:16)
    at Object.resolveList (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/value-promise.js:131:32)
    at resolveInjectedArguments (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolver.js:158:28)
    at Object.instantiateClass (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolver.js:39:27)
    at Binding._getValue (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/binding.js:388:55)
    at resolution_session_1.ResolutionSession.runWithBinding.s (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/binding.js:206:90)
    at value_promise_1.tryWithFinally (../LB4RequestbodyValidation/node_modules/@loopback/context/dist/resolution-session.js:69:53)`

You can find it in this [repo](https://github.com/frodoe7/LB4RequestbodyValidation)

However, the second option (which I have been already using) is working without a problem:
```js
      content: {
        'application/json': {
          schema: {
            type: 'object',
            additionalProperties: false,
            properties: {
              id: {type: 'string'},
              age: {type: 'number'}
            },
            required: ['id', 'age'],
          },
        },
```

But of course, it will be better in my view to have a model used for validation instead of manually adding the properties. So it would be great if we get option 1 to work.

**Comment by bajtos** [comment]
> I have tried the first option. Unfortunately, it gives the following error:
> ```
> Unhandled error in PUT /tests: 500 Error: The key 'repositories.TestRepository' 
> is not bound to any value in context 0c7f5a30-4fd2-11e9-8580- 2faabf6cb00d
> ```

That problem looks unrelated to model validation, at least I don't see any obvious reason how using `class idAndAge {` can trigger it. Is it possible that your application is misconfigured in the sense that the repository class is either not bound at all, or is bound under a different key?

I am afraid I don't have bandwidth to look into this in more details right now. If you manage to find any new information, then feel free to open a new issue. Just make sure to create a sandbox app per our [bug reporting instructions](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs).
