### ISSUE TITLE
Issue with .mocharc.json file attribute

### ISSUE THREAD

**Issue by ThePinger** [strongloop/loopback-next#2677]
## I have a problem when adding file attribute in .mocharc.json

I created a loopback4 project and here's the repo link https://github.com/ThePinger/first-project , However when I run ```npm test``` I get that error caused by the import statement in setup.ts.

```
/Users/omaremad/Desktop/first-project/src/__tests__/setup.ts:1
(function (exports, require, module, __filename, __dirname) { import {add} from './acceptance/test-helper';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /Users/omaremad/Desktop/first-project/node_modules/mocha/lib/mocha.js:327:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/omaremad/Desktop/first-project/node_modules/mocha/lib/mocha.js:324:14)
    at Mocha.run (/Users/omaremad/Desktop/first-project/node_modules/mocha/lib/mocha.js:801:10)
    at Object.exports.singleRun (/Users/omaremad/Desktop/first-project/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/Users/omaremad/Desktop/first-project/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/Users/omaremad/Desktop/first-project/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/Users/omaremad/Desktop/first-project/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/omaremad/Desktop/first-project/node_modules/yargs/yargs.js:1072:28)
    at Object.parse (/Users/omaremad/Desktop/first-project/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/omaremad/Desktop/first-project/node_modules/mocha/lib/cli/cli.js:62:6)
    at Object.<anonymous> (/Users/omaremad/Desktop/first-project/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

Here's the ```.mocharc.json```
```Json
{
  "file": "./src/__tests__/setup.ts",
  "recursive": true,
  "require": "source-map-support/register"
}
```
and here's the setup.ts file content 
```ts
import {add} from './acceptance/test-helper';

before('Execute some function', async () => {
  console.log(add(2, 3));
});
```
and here's the function in /\_\_tests__/acceptance/test-helper.ts

```ts
export async function add(x: any, y: any) {
  console.log('HAAAAAAA');
  return x + y;
}
```
So does anybody know why this error comes in that file only and what's the solution in order to run a certain file before all the tests ??

**Comment by raymondfeng** [comment]
You should add the `.js` file under `dist`.

**Comment by ThePinger** [comment]
@raymondfeng Well that worked well thanks a lot 😉😉
