### ISSUE TITLE
Loopback 4 crashes when fetch entity that has embedded object from MongoDb

### ISSUE THREAD

**Issue by Sarkhad** [strongloop/loopback-next#2726]
When loopback trying to fetch entities it crashes. But writing to a database works properly. Stack trace below:

`Server is running at http://127.0.0.1:3000
Try http://127.0.0.1:3000/ping
C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\utils.js:132
      throw err;
      ^

TypeError: Cannot read property 'properties' of undefined
    at MongoDB.fromDatabase (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\loopback-connector-mongodb\lib\mongodb.js:371:25)
    at MongoDB.fromDatabase (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\loopback-connector-mongodb\lib\mongodb.js:396:22)
    at C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\loopback-connector-mongodb\lib\mongodb.js:1358:18
    at Array.map (<anonymous>)
    at C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\loopback-connector-mongodb\lib\mongodb.js:1349:23
    at result (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\utils.js:414:17)
    at executeCallback (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\utils.js:406:9)
    at handleCallback (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\utils.js:128:55)
    at cursor.close (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\operations\cursor_ops.js:224:62)
    at handleCallback (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\utils.js:128:55)
    at completeClose (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\cursor.js:893:14)
    at Cursor.close (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\cursor.js:912:10)
    at cursor._next (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb\lib\operations\cursor_ops.js:224:23)
    at handleCallback (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb-core\lib\cursor.js:204:5)
    at _setCursorNotifiedImpl (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb-core\lib\cursor.js:433:38)
    at self._endSession (C:\Users\DABRYNIN_AA\WebstormProjects\rfu-digital-backend\node_modules\mongodb-core\lib\cursor.js:441:46)
`

Code of entities used:
Entity
`import { Entity, model, property } from '@loopback/repository';
import {Product} from './product.model';
import {OrderDetails} from './orderdetails.model';

@model()
export class Order extends Entity {

  @property({
    type: 'number',
    id: true,
  })
  id: number;

  @property({
    type: 'string',
    required: true,
  })
  content: string;

  @property.array(Product)
  products: Product[];

  @property({
    type: OrderDetails
  })
  details: OrderDetails;

  constructor(data?: Partial<Order>) {
    super(data);
  }
}`
Embedded object
`import { model, property, Model } from '@loopback/repository';

@model()
export class OrderDetails extends Model {

  @property({
    type: 'number',
  })
  numberOfItems: number;

  @property({
    type: 'string',
  })
  comment: string;

}
`

Embedded list item

`import { model, property, Model } from '@loopback/repository';

@model()
export class Product extends Model {

  @property({
    type: 'string',
  })
  content: string;

  constructor(data?: Partial<Product>) {
    super(data);
  }
}
`

Repository:

`
import {DefaultCrudRepository} from '@loopback/repository';
import {Order} from '../models';
import {inject} from '@loopback/core';
import {DbDataSource} from '../datasources';

export class OrderRepository extends DefaultCrudRepository<
  Order,
  typeof Order.prototype.id
> {
  constructor(
    @inject('datasources.db') dataSource: DbDataSource,
  ) {
    super(Order, dataSource);
  }
}
`

**Comment by dhmlau** [comment]
Transferring to `loopback-next` repo.

**Comment by dhmlau** [comment]
@Sarkhad , does the above comment help with your issue?  Thanks.

**Comment by Sarkhad** [comment]
> @Sarkhad, does the above comment help with your issue? Thanks.

Yes, It does. Also works properly annotated with 'object' type. IMHO It's not documented behavior/case, so I guess this ticket would help others to find the solution.

**Comment by dhmlau** [comment]
@Sarkhad, that's good point.  Let me see how I can put that information in. Thanks for your feedback!
