### ISSUE TITLE
Using @loopback/context in JS application

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next#2784]
## Description / Steps to reproduce / Feature proposal

We are trying to use `@loopback/context` in our application (its in Javascript, not typescript) and its throwing error (given below).

Is there any sample code which give more idea how to implement `@loopback/context` in JS applications ?

Code:

```js
const {Context} = require('@loopback/context');
const ctx = new Context();

// bind 'greeting' to 'Hello' as the constant value
ctx.bind('greeting').to('Hello');

class HelloController {
  constructor(greeting) {
      this.greeting = greeting;
  }

  greet(name) {
    return `${this.greeting}, ${name}`;
  }
}

// // Bind 'HelloController' to class HelloController
ctx.bind('HelloController').toClass(HelloController);

async function hello() {
  // Get an instance of HelloController
  const helloController = await ctx.get('HelloController');
  // helloController now has the `greeting` property injected with `Hello`
  console.log(helloController.greet('John')); // => Hello, John
}

hello();
```

## Current Behavior
Currently, we are getting error like below,
```
Error: Cannot resolve injected arguments for HelloController.[0]: The arguments[0] is not decorated for dependency injection, but a value is not supplied
    at value_promise_1.resolveList (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\resolver.js:171:23)
    at Object.resolveList (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\value-promise.js:131:32)
    at resolveInjectedArguments (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\resolver.js:159:28)
    at Object.instantiateClass (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\resolver.js:39:27)
    at Binding._setValueGetter [as _getValue] (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\binding.js:393:59)
    at resolution_session_1.ResolutionSession.runWithBinding.s (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\binding.js:199:29)
    at value_promise_1.tryWithFinally (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\resolution-session.js:69:53)
    at Object.tryWithFinally (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\value-promise.js:158:18)
    at Function.runWithBinding (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\resolution-session.js:69:32)
    at Binding.getValue (C:\workspace\samples\babel\es7\node_modules\@loopback\context\dist\binding.js:197:65)
```

**Comment by dhmlau** [comment]
@hacksparrow, could you please take a look?  Not sure if you've looked into context when working on the JavaScript experience spike. 

@rahulrkr08, may I know the reason you're using JavaScript for LoopBack 4?  Are you using `@loopback/context` as a separate component?  Would be interested to know about your use case. Thanks!  On a similar note, we have a blog post on experimenting JavaScript experience in LB4: https://strongloop.com/strongblog/loopback4-javascript-experience/.

**Comment by raymondfeng** [comment]
@rahulrkr08 In your case, the constructor parameter is missing a decorator, which is critical for dependency injection. @hacksparrow put together an example at https://github.com/strongloop/loopback4-example-javascript/blob/stage-f/server/controllers/color.controller.js. Please check out.

**Comment by rahulrkr08** [comment]
Thanks @raymondfeng, the given solution worked. Is there any documentation for this ?
@dhmlau Yes, we are using `@loopback/context` as separate component for IoC container.

**Comment by hacksparrow** [comment]
@rahulrkr08 we don't have documentation for it, since we are get to conclude on an "official" approach. You can look at this example app for the undocumented approach to using LB4 with JavaScript - https://github.com/strongloop/loopback4-example-javascript/tree/class-factory.

If it is not much of a trouble, we recommend to use TypeScript with LB4.

**Comment by dhmlau** [comment]
Closing this issue as answered.
