### ISSUE TITLE
npm start fails after running npm run clean

### ISSUE THREAD

**Issue by Mmalumbo** [strongloop/loopback-next#3197]
## Steps to reproduce
* Scaffold a new app [getting started](http://v4.loopback.io/getting-started.html)
* go into the project directory `cd project-name`
* run `npm run clean` followed by `npm start`

### loopback version

```
@loopback/cli version: 1.17.1

@loopback/* dependencies:
  - @loopback/authentication: ^2.1.3
  - @loopback/boot: ^1.4.2
  - @loopback/build: ^2.0.1
  - @loopback/context: ^1.20.0
  - @loopback/core: ^1.8.3
  - @loopback/metadata: ^1.2.3
  - @loopback/openapi-spec-builder: ^1.2.3
  - @loopback/openapi-v3-types: ^1.1.3
  - @loopback/openapi-v3: ^1.6.3
  - @loopback/repository-json-schema: ^1.7.1
  - @loopback/repository: ^1.8.0
  - @loopback/rest: ^1.16.1
  - @loopback/testlab: ^1.6.1
  - @loopback/docs: ^1.24.0
  - @loopback/example-hello-world: ^1.2.3
  - @loopback/example-log-extension: ^1.2.3
  - @loopback/example-rpc-server: ^1.2.3
  - @loopback/example-todo: ^1.6.3
  - @loopback/example-soap-calculator: ^1.6.4
  - @loopback/service-proxy: ^1.2.3
  - @loopback/http-caching-proxy: ^1.1.3
  - @loopback/http-server: ^1.4.2
  - @loopback/example-todo-list: ^1.7.3
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.2.3
  - @loopback/eslint-config: ^1.1.2
  - @loopback/example-express-composition: ^1.4.3
  - @loopback/example-greeter-extension: ^1.3.3
  - @loopback/booter-lb3app: ^1.2.3
  - @loopback/example-lb3-application: ^1.1.3
  - @loopback/example-greeting-app: ^1.1.3
  - @loopback/example-context: ^1.2.3
  - @loopback/repository-tests: ^0.2.0
```

## Current Behavior
After running the following npm commands:

```sh
npm run clean
npm start
```

i get the error bellow:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/mmalumbo/Dev/ebes/malu/index.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

### Note:
The problem goes away when i change the version of typescript and i reinstall it but when i run clean again, the problem appears again. Am switching between typescript 3.4.5 and 3.5.2 to make the project work. 
This fix is tiresome and its finishing my data bundle, as a result, a permanent fix will help.

## Expected Behavior
The project should execute.

**Comment by raymondfeng** [comment]
Try to remove `tsconfig.build.tsbuildinfo` and run the command again. The latest version should have the file removed as part of `npm run clean`.

**Comment by Mmalumbo** [comment]
@raymondfeng thanks, removing the file worked but running `npm run clean` is not removing the `tsconfig.build.tsbuildinfo` file. 

I am using the version bellow:

```
backend git:(add-models) ✗ lb4 --v
@loopback/cli version: 1.17.1
```

I will wait for the new version. Thanks again.

**Comment by raymondfeng** [comment]
Hmm, the generated project uses `tsconfig.json`. As a result, the clean script should remove `tsconfig.tsbuildinfo` instead of `tsconfig.build.tsbuildinfo`.

**Comment by CollinHerber** [comment]
@raymondfeng I am running into this problem now. 
```
lb4 -version
@loopback/cli version: 1.24.0
```

I've manually deleted the tsbuildinfo file, and ensured all my packages are up to date.

```
C:\nvm\v10.16.3\node.exe C:\nvm\v10.16.3\node_modules\npm\bin\npm-cli.js run start --scripts-prepend-node-path=auto

> *-lb4@1.0.0 prestart C:\Users\*\Desktop\dev\*\api-v2
> npm run build


> *-lb4@1.0.0 build C:\Users\*\Desktop\dev\*\api-v2
> lb-tsc


> *@1.0.0 start C:\Users\*\Desktop\dev\*\api-v2
> node -r source-map-support/register .

Error: Cannot find module 'C:\Users\*\Desktop\dev\*\api-v2'
```

For me it almost looks like it's not going to the /dist folder for the program. Where is this specified?

Here is my pacakge.json
```
{
  "name": "*",
  "version": "1.0.0",
  "description": "*",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8.9"
  },
  "scripts": {
    "build": "lb-tsc",
    "build:watch": "lb-tsc --watch",
    "clean": "lb-clean dist *.tsbuildinfo",
    "lint": "npm run prettier:check && npm run eslint",
    "lint:fix": "npm run eslint:fix && npm run prettier:fix",
    "prettier:cli": "lb-prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write",
    "eslint": "lb-eslint --report-unused-disable-directives .",
    "eslint:fix": "npm run eslint -- --fix",
    "pretest": "npm run clean && npm run build",
    "posttest": "npm run lint",
    "docker:build": "docker build -t * .",
    "docker:run": "docker run -p 3000:3000 -d *",
    "migrate": "node ./dist/migrate",
    "prestart": "npm run build",
    "start": "node -r source-map-support/register .",
    "prepublishOnly": "npm run test"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "src"
  ],
  "dependencies": {
    "@loopback/boot": "^1.5.9",
    "@loopback/booter-lb3app": "^1.3.3",
    "@loopback/context": "^1.23.3",
    "@loopback/core": "^1.10.5",
    "@loopback/openapi-v3": "^1.9.10",
    "@loopback/rest": "^1.21.0",
    "@loopback/rest-explorer": "^1.4.2",
    "@sendgrid/mail": "^6.4.0",
    "coinbase": "^2.0.8",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "helmet": "^3.21.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.15",
    "loopback": "^3.26.0",
    "loopback-boot": "3.3.1",
    "loopback-component-storage": "^3.6.3",
    "loopback-connector-mysql": "^5.4.2",
    "loopback-context": "~3.3.0",
    "moment": "~2.19.2",
    "numeral": "^2.0.6",
    "qrcode": "^1.4.2",
    "request": "^2.88.0",
    "request-promise": "^4.2.4",
    "serve-favicon": "^2.5.0",
    "speakeasy": "^2.0.0"
  },
  "devDependencies": {
    "@loopback/build": "^2.0.14",
    "source-map-support": "^0.5.13",
    "@loopback/testlab": "^1.9.2",
    "@types/node": "^10.14.20",
    "@typescript-eslint/parser": "^2.3.3",
    "@typescript-eslint/eslint-plugin": "^2.3.3",
    "@loopback/eslint-config": "^4.1.2",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.4.0",
    "eslint-plugin-eslint-plugin": "^2.1.0",
    "eslint-plugin-mocha": "^6.1.1",
    "typescript": "~3.6.3"
  }
}
```

Note: I have * where all my project names, this is not a mistake.

**Comment by raymondfeng** [comment]
@CollinHerber Check you if you have `api-v2/index.js`?

**Comment by CollinHerber** [comment]
@raymondfeng I do and this is what is in it: `export * from './src';`

**Comment by raymondfeng** [comment]
index.js or index.ts?

**Comment by CollinHerber** [comment]
Ohh sorry. It is `index.ts`, there is no `index.js`

**Comment by raymondfeng** [comment]
You should have `index.js` as follows:
```js
const application = require('./dist');

module.exports = application;

if (require.main === module) {
  // Run the application
  const config = {
    rest: {
      port: +(process.env.PORT || 3000),
      host: process.env.HOST,
      openApiSpec: {
        // useful when used with OpenAPI-to-GraphQL to locate your application
        setServersFromRequest: true,
      },
    },
  };
  application.main(config).catch(err => {
    console.error('Cannot start the application.', err);
    process.exit(1);
  });
}
```

**Comment by CollinHerber** [comment]
@raymondfeng Yes, thank you. Good catch. Im confused why my source control didn't bring it in. Anyways, thank you for the assistance!
