### ISSUE TITLE
(lb2) lb3 ->lb4  notes example / instructions to add that may help other users. 

### ISSUE THREAD

**Issue by johndpope** [strongloop/loopback-next#3210]
## Description / Steps to reproduce / Feature proposal

<img width="1136" alt="Screen Shot 2019-06-22 at 6 02 01 pm" src="https://user-images.githubusercontent.com/289994/59961200-f0e77d80-9517-11e9-8cca-03f2f8360aa4.png">

## Current Behavior
example missing extra steps that maybe helpful to others..

## Expected Behavior
add steps to remove 

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by johndpope** [comment]
When I upgraded v2->v3 -> v4 
I got stuck on error below. 


```shell

Unhandled rejection Error: Callback was already called.
at /Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/async/dist/async.js:966:32
at executePluginPhase (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/loopback-boot/lib/bootstrapper.js:177:7)
at /Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/async/dist/async.js:3110:16
at replenish (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/async/dist/async.js:1011:17)
at iterateeCallback (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/async/dist/async.js:995:17)
at /Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/async/dist/async.js:969:16
at onPluginPhaseResolved (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/loopback-boot/lib/bootstrapper.js:169:13)
at tryCatcher (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/promise.js:517:31)
at Promise._settlePromise (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/promise.js:574:18)
at Promise._settlePromiseCtx (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/promise.js:611:10)
at _drainQueueStep (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/async.js:142:12)
at _drainQueue (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.Async.drainQueues [as _onImmediate] (/Users/johndpope/Documents/gitWorkspace/loopback-next/examples/lb3-application/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:705:18)
```

for reference -  in my server **boot** folder - there was a Explorer.js - 
deleting this file resolved this obscure error. The new explorer just works out of the box. 

<img width="1229" alt="Screen Shot 2019-06-22 at 11 12 17 pm" src="https://user-images.githubusercontent.com/289994/59964390-3cfbe780-9543-11e9-9cc0-853b40eedb86.png">

 If your app doesn't boot - one option maybe to troubleshoot by removing stuff from this folder.

**Comment by dhmlau** [comment]
@nabdelgadir, could you please take a look? Thanks.

**Comment by johndpope** [comment]
This isn't so much an issue ticket - just captured some of my own woes upgrading to loopback 4 that may help others. the big one was ditching  Explorer.js from boot up.

**Comment by dhmlau** [comment]
Thanks @johndpope. If there's some additional content that can help other users, could you please submit a PR to help improving our docs? Thanks!

**Comment by nabdelgadir** [comment]
Let us know if you need any help; here's a guide for [Submitting a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html). 😄

**Comment by johndpope** [comment]
might be an idea to sufface this as a tool to help people upgrade old code https://www.npmjs.com/package/js-to-ts-converter

**Comment by dhmlau** [comment]
@johndpope, thanks for the link.  On a related note, we have a [spike on the migration guide](https://github.com/strongloop/loopback-next/issues/3718) planned for this month.  I'd encourage you to stay tune with the progress over there and provide your input!
