### ISSUE TITLE
Support model property type "any"

### ISSUE THREAD

**Issue by 1057437122** [strongloop/loopback-next#3386]
I created a model with lb4 and success migrated , but when I start the application it told me start failed , why is this ?How can i solve this ?
```
>node .
Cannot start the application. Error: Unsupported type: any
    at stringTypeToWrapper (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/repository-json-schema/dist/build-schema.js:130:19)
    at metaToJsonProperty (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/repository-json-schema/dist/build-schema.js:162:25)
    at modelToJsonSchema (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/repository-json-schema/dist/build-schema.js:254:32)
    at Object.getJsonSchema (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/repository-json-schema/dist/build-schema.js:38:18)
    at generateOpenAPISchema (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/openapi-v3/dist/controller-spec.js:198:49)
    at processSchemaExtensions (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/openapi-v3/dist/controller-spec.js:165:13)
    at resolveControllerSpec (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/openapi-v3/dist/controller-spec.js:66:17)
    at Object.getControllerSpec (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/openapi-v3/dist/controller-spec.js:237:16)
    at RestServer._setupHandlerIfNeeded (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/rest/dist/rest.server.js:212:42)
    at RestServer.start (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/rest/dist/rest.server.js:528:14)
    at LifeCycleObserverRegistry.invokeObserver (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/core/dist/lifecycle-registry.js:123:34)
    at observers.map (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/core/dist/lifecycle-registry.js:112:25)
    at Array.map (<anonymous>)
    at LifeCycleObserverRegistry.notifyObservers (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/core/dist/lifecycle-registry.js:110:37)
    at LifeCycleObserverRegistry.notifyGroups (/Users/work/Documents/Program/Javascript/nodejs/loopback/webback/node_modules/@loopback/core/dist/lifecycle-registry.js:149:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

**Comment by bajtos** [comment]
@1057437122 thank you for reporting the issue. Please create a small app we can use to reproduce the problem, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

We don't support `any` type in LoopBack 4. It's not supported by OpenAPI (Swagger) either.

**Comment by 1057437122** [comment]
> @1057437122 thank you for reporting the issue. Please create a small app we can use to reproduce the problem, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs
> 
> We don't support `any` type in LoopBack 4. It's not supported by OpenAPI (Swagger) either.

not supported ?But the type "any" was create by lb4 model :
![image](https://user-images.githubusercontent.com/6631168/61454183-6fd9a580-a960-11e9-96ef-619b94fe10b7.png)
if lb4 dont support `any` then what type should i use to create a  long text column ?

**Comment by jvacas** [comment]
> @1057437122 thank you for reporting the issue. Please create a small app we can use to reproduce the problem, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs
> 
> We don't support `any` type in LoopBack 4. It's not supported by OpenAPI (Swagger) either.

I think it's supported by openapi. In the [docs](https://swagger.io/docs/specification/data-models/data-types/) saids:

> Any Type
> A schema without a type matches any data type – numbers, strings, objects, and so on. {} is shorthand syntax for an arbitrary-type schema

**Comment by bajtos** [comment]
Thank you for the comments. It looks like my understanding of `any` in LB4 was based on a wrong assumption and we need to look deeper into this topic.

> if lb4 dont support any then what type should i use to create a long text column ?

I would use `string` type. It's possible to configure the property to map to a different database column type - see https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#data-mapping-properties (the docs is for LB3 but applies to LB4 too).

> https://swagger.io/docs/specification/data-models/data-types/#any
> Any Type
> A schema without a type matches any data type – numbers, strings,  objects, and so on. {} is shorthand syntax for an arbitrary-type schema

Interesting, I was not aware of this bit. 

We are converting OpenAPI schemas to JSON Schemas so that we can use [AJV](https://www.npmjs.com/package/ajv) to validate incoming data, we will need to verify that `AJV` treats a schema with no type as "any type" too.

My conclusion is that we need to:
- Modify [packages/repository-json-schema/src/build-schema.js](https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts) to correctly recognize `any` type, include new tests in `repository-json-schema` to validate
- Add new tests to `packages/rest` to verify that `any` type is correctly validated by the REST API layer

@1057437122 @jvacas would you like to contribute these changes yourself? We are happy to help you along the way, here are few resources to get you started: [Contributing code in LoopBack 4](https://loopback.io/doc/en/contrib/code-contrib-lb4.html) and [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).

**Comment by jvacas** [comment]
I made some tests and found a little workaround for the schema generation/AJV, if you define the property this way it works as an any type

`@property({
    jsonSchema: {
      type: AnyType,
    },
  })`

the problem then falls on juggler that doesn't recognize the type and tries to save the data as an object.

**Comment by 1057437122** [comment]
> Thank you for the comments. It looks like my understanding of `any` in LB4 was based on a wrong assumption and we need to look deeper into this topic.
> 
> > if lb4 dont support any then what type should i use to create a long text column ?
> 
> I would use `string` type. It's possible to configure the property to map to a different database column type - see https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#data-mapping-properties (the docs is for LB3 but applies to LB4 too).
> 
> > https://swagger.io/docs/specification/data-models/data-types/#any
> > Any Type
> > A schema without a type matches any data type – numbers, strings,  objects, and so on. {} is shorthand syntax for an arbitrary-type schema
> 
> Interesting, I was not aware of this bit.
> 
> We are converting OpenAPI schemas to JSON Schemas so that we can use [AJV](https://www.npmjs.com/package/ajv) to validate incoming data, we will need to verify that `AJV` treats a schema with no type as "any type" too.
> 
> My conclusion is that we need to:
> 
> * Modify [packages/repository-json-schema/src/build-schema.js](https://github.com/strongloop/loopback-next/blob/master/packages/repository-json-schema/src/build-schema.ts) to correctly recognize `any` type, include new tests in `repository-json-schema` to validate
> * Add new tests to `packages/rest` to verify that `any` type is correctly validated by the REST API layer
> 
> @1057437122 @jvacas would you like to contribute these changes yourself? We are happy to help you along the way, here are few resources to get you started: [Contributing code in LoopBack 4](https://loopback.io/doc/en/contrib/code-contrib-lb4.html) and [Submitting a pull request to LoopBack 4](https://loopback.io/doc/en/lb4/submitting_a_pr.html).

I would like to contribute some changes  but now I'm new to loopback ,so if I can do i will do it in the future ,thank you , now i will try to change type "any" to "string" to  finish my job first.
