### ISSUE TITLE
lb4 example todo geo coding example typescript error

### ISSUE THREAD

**Issue by jordo1138** [strongloop/loopback-next#3510]
`Unhandled error in POST /todos: 500 TypeError: Cannot read property 'y' of undefined
    at TodoController.createTodo (/loopback/examples/loopback4-example-todo/dist/controllers/todo.controller.js:37:42)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`

This error occures when trying out the tutorial
https://loopback.io/doc/en/lb4/todo-tutorial-geocoding-service.html
The geo coding service is supposed to work for POST /todos with the address string
This error occurs if you use the remindAtAddress option when posting

I tried both by setting up the tutorial step by step and using the lb4 example todo code
both cases have this error of property 'y' of undefined
{
  "id": 0,
  "title": "string",
  "desc": "string",
  "isComplete": true,
  "remindAtAddress": "string",
  "remindAtGeo": "string"
}

**Comment by jordo1138** [comment]
issue is that the address in the string cannot just be city state zip code, it may not return results and then this will cause Y to be undefined
