### ISSUE TITLE
mongodb connector config url must be url encoded to be able to connect to Azure

### ISSUE THREAD

**Issue by sandijs-private** [strongloop/loopback-next#3531]
## Steps to reproduce

When using Azure CosmosDB mongodb, they generate passwords with special characters which need to be url encoded.

Loopback mongo db connector config then looks like this:

{
  "name": "database",
  "connector": "mongodb",
  "url": "mongodb://some-user:password==@some-project.documents.azure.com:10255/somedatabase?ssl=true&replicaSet=globaldb",
  "useNewUrlParser": true
}

That causes Loopback node.js instance crash:

/Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/url_parser.js:134
  return err ? callback(err, null) : callback(null, result);
               ^
TypeError: Cannot read property 'dbName' of null
    at /Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:310:17
    at parseHandler (/Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/url_parser.js:134:16)
    at module.exports (/Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/url_parser.js:25:12)
    at /Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:308:16
    at /Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/utils.js:410:17
    at executeCallback (/Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/utils.js:402:9)
    at /Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/operations/mongo_client_ops.js:286:5
    at connectCallback (/Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/operations/mongo_client_ops.js:265:5)
    at /Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/operations/mongo_client_ops.js:417:5
    at ReplSet.connectHandler (/Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb/lib/topologies/replset.js:343:9)
    at Object.onceWrapper (events.js:291:20)
    at ReplSet.emit (events.js:203:13)
    at /Users/sandijs/Documents/loopback/business-ideas-generator-server/node_modules/mongodb-core/lib/topologies/replset.js:538:20
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

## How to fix

Config with url encoded works as expected:

(notice those %3D%3D in the password!)

{
  "name": "database",
  "connector": "mongodb",
  "url": "mongodb://some-user:password%3D%3D@some-project.documents.azure.com:10255/somedatabase?ssl=true&replicaSet=globaldb",
  "useNewUrlParser": true
}

There is no need for Sandbox, as this is trivial-classical bug since the beginning of the web projects.

**Comment by hacksparrow** [comment]
Thanks @sandijs-private.

This issue has been reported earlier too, it was concluded as a documentation issue and we landed a PR - https://github.com/strongloop/loopback-connector-mongodb/pull/529 - to resolve it.
