### ISSUE TITLE
Bug: Circular related model at getModelSchemaRef(...,{includeRelations: true})

### ISSUE THREAD

**Issue by koliberr136a1** [strongloop/loopback-next#3603]
## Steps to reproduce

1. Create a model with **circular relation** like bellow:

```ts
@model({ settings: {} })
export class MyModel extends Entity {
    @property({
        type: "string",
        id: true,
        required: true,
        defaultFn: "uuidv4"
    })
    id: string;

    @belongsTo(() => MyModel)
    parentId: string;

    constructor(data?: Partial<MyModel>) {
        super(data);
    }
}

export interface MyModelRelations {
    parent: MyModelWithRelations;
}

export type MyModelWithRelations = MyModel & MyModelRelations;
```

2. Try to log `getModelSchemaRef` of the model with `includeRelations` flag to `true`

```ts
console.log(getModelSchemaRef(MyModel, { includeRelations: true }));
```

## Current Behavior

Your test will throws exception with these log:

```code
Cannot start the application. TypeError: Cannot set property 'MyModelWithRelations' of undefined
    at includeReferencedSchema (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/repository-json-schema/dist/build-schema.js:325:34)
    at modelToJsonSchema (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/repository-json-schema/dist/build-schema.js:311:13)
    at getJsonSchema (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/repository-json-schema/dist/build-schema.js:43:18)
    at Object.getJsonSchemaRef (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/repository-json-schema/dist/build-schema.js:83:35)
    at Object.getModelSchemaRef (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/openapi-v3/dist/controller-spec.js:267:49)
    at Object.getModelSchemaRef (/home/koliber/Workspace/dms-server/sources/build/servers/rest/controller.js:79:30)
    at Object.<anonymous> (/home/koliber/Workspace/dms-server/sources/build/servers/rest/controllers/document/document.controller.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.loadClassesFromFiles (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/boot/dist/booters/booter-utils.js:47:27)
    at ControllerBooter.load (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/boot/dist/booters/base-artifact.booter.js:84:39)
    at ControllerBooter.load (/home/koliber/Workspace/dms-server/sources/node_modules/@loopback/boot/dist/booters/controller.booter.js:47:21)
```

## Expected Behavior

Logs schema:

```json
{
    "$ref": "#/components/schemas/MyModelWithRelations",
    "definitions": {
        "MyModelWithRelations": {
            "title": "MyModelWithRelations",
            "properties": [Object],
            "required": [Array]
        }
    }
}
```

## Additional information

```code
linux x64 12.8.1

├── @loopback/authentication@2.1.11
├── @loopback/boot@1.5.3
├── @loopback/context@1.21.4
├── @loopback/core@1.9.3
├── @loopback/openapi-v3@1.9.4
├── @loopback/repository@1.12.0
├── @loopback/rest@1.17.0
├── @loopback/rest-explorer@1.3.4
├── @loopback/service-proxy@1.3.3
├── loopback-authorization-extension@0.6.2
├── loopback-connector-kv-redis@3.0.1
├── loopback-connector-mysql@5.4.2
npm ERR! extraneous: @types/jest@24.0.15 /home/koliber/Workspace/dms-server/sources/node_modules/memoizor/node_modules/@types/jest
npm ERR! extraneous: @types/node@12.0.10 /home/koliber/Workspace/dms-server/sources/node_modules/memoizor/node_modules/@types/node
npm ERR! extraneous: jest@24.8.0 /home/koliber/Workspace/dms-server/sources/node_modules/memoizor/node_modules/jest
npm ERR! extraneous: ts-jest@24.0.2 /home/koliber/Workspace/dms-server/sources/node_modules/memoizor/node_modules/ts-jest
npm ERR! extraneous: typescript@3.5.2 /home/koliber/Workspace/dms-server/sources/node_modules/memoizor/node_modules/typescript
```

## See the bug

I traced this file: `repository-json-schema/src/build-schema.ts`, and I find the problem is the links of objects:

https://github.com/strongloop/loopback-next/blob/554c763aa5c8db92bb4c3e5549960b8a99673791/packages/repository-json-schema/src/build-schema.ts#L399-L406

When I've tried to run `console.log(result.definitions);` after line `405`, I got **undefined**

I found that **`result`** and **`targetSchema`** variables have same object reference

## Solve the bug

We need to copy the schema returned by `getJsonSchema`:

https://github.com/strongloop/loopback-next/blob/554c763aa5c8db92bb4c3e5549960b8a99673791/packages/repository-json-schema/src/build-schema.ts#L100

We can fix the problem using `return Object.assign({}, schema);`

When I changed the code in `build-schema.js`, **the problem solved**

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by koliberr136a1** [comment]
Isn't there any solution for this problem ? @dhmlau  @bajtos

**Comment by dhmlau** [comment]
There's a section in the documentation https://loopback.io/doc/en/lb4/BelongsTo-relation.html#handling-recursive-relations that covers circular dependencies.  @koliberr136a1, could you please take a look and see if it helps?

**Comment by koliberr136a1** [comment]
Thanks @dhmlau , I've used this documentation to implement my Models and Repositories, but this bug is about openapi-spec generation and `getModelSchemaRef` method

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-next/pull/3674. We'll make a new release soon.
