### ISSUE TITLE
Unable to create Recursive Model (Non Entity)

### ISSUE THREAD

**Issue by mmussche2** [strongloop/loopback-next#3671]
## Steps to reproduce
I have a non Entity Model ReportState which needs to contain an array of ReportStates, It has no ID and is not persisted, it is just part of another model. When starting the API it crashes. Here is my Model : 
```
export class ReportState extends Model {

  @property.array(ReportState, {})
  states: ReportState[];

  @property({
    type: 'string',
  })
  benchmarkId?: string;

  @property({
    type: 'string',
  })
  color?: string;

  constructor(data?: Partial<ReportState>) {
    super(data);
  }
```

## Current Behavior

```
TypeError: Cannot set property 'ReportState' of undefined
    at includeReferencedSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:321:38)
    at modelToJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:292:9)
    at getJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:40:18)
    at modelToJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:291:28)
    at getJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:40:18)
    at modelToJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:291:28)
    at getJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:40:18)
    at modelToJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:291:28)
    at Object.getJsonSchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\repository-json-schema\dist\build-schema.js:40:18)
    at generateOpenAPISchema (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\openapi-v3\dist\controller-spec.js:198:49)
    at processSchemaExtensions (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\openapi-v3\dist\controller-spec.js:165:13)
    at resolveControllerSpec (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\openapi-v3\dist\controller-spec.js:66:17)
    at Object.getControllerSpec (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\openapi-v3\dist\controller-spec.js:237:16)
    at RestServer._setupHandlerIfNeeded (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\rest\dist\rest.server.js:212:42)
    at RestServer.start (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\rest\dist\rest.server.js:529:14)
    at LifeCycleObserverRegistry.invokeObserver (C:\Users\mmussche\Documents\workspace\Boccard\ta-api-core-2\node_modules\@loopback\core\dist\lifecycle-registry.js:123:34)
```

## Expected Behavior

I'd want it to start correctly and have the api spec to show that this model is recursive.

## Additional information

Replacing the type of states with an array of objects is a work around, but the spec is less precise that way.

## Related Issues

#2250

**Comment by dhmlau** [comment]
The example given in this issue is a bit different from #2250 in the sense that it doesn't involve any model relation. Therefore, the [docs changes](https://loopback.io/doc/en/lb4/BelongsTo-relation.html#handling-recursive-relations) from #2250 are not applicable. 

I've created a sample repo to try it out: https://github.com/dhmlau/loopback4-recursive-example. I've made some slight modification to have an id in the model. 

@strongloop/loopback-maintainers,  do you think it's a bug? Or there's other way to define the model? Thanks.

**Comment by bajtos** [comment]
Thank you @mmussche2 for reporting the issue. I landed @raymondfeng's patch https://github.com/strongloop/loopback-next/pull/3674, the fix will be available in the next release.

**Comment by mmussche2** [comment]
Thank you for the quick feedback on this issue, I'm waiting for the next release now.

**Comment by mmussche2** [comment]
Hello again @bajtos @raymondfeng,
I have updated my openapi-v3 dependency, now my API starts correctly, but I can't send a post on the associated endpoint, I get an internal server error : 
```
{
    "error": {
        "statusCode": 500,
        "name": "RangeError",
        "message": "Maximum call stack size exceeded",
        "stack": "RangeError: Maximum call stack size exceeded\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:95:43)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)\n    at Object.entries.forEach (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:96:51)\n    at Array.forEach (<anonymous>)\n    at ReportDefinitionRepository.definePersistedModel (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:91:47)\n    at ReportDefinitionRepository.resolvePropertyType (C:\\Users\\mmussche\\Documents\\workspace\\Boccard\\ta-api-core-2\\node_modules\\@loopback\\repository\\dist\\repositories\\legacy-juggler-bridge.js:120:20)"
    }
}
```

when replacing 
 ```
@property.array(ReportState, {})
  states: ReportState[];
```
by 
```
 @property.array(Object, {})
  states: ReportState[];
```
it works, but then the recursive model is not specified
