### ISSUE TITLE
app.migrateSchema is not a function

### ISSUE THREAD

**Issue by CNSKnight** [strongloop/loopback-next#4002]
## Steps to reproduce

- mount lb3 src artifacts in fresh lb4 app / get it working
- lb-tcs (w/defaults)
- node ./dist/migrate

## Current Behavior

emits
```
Migrating schemas (alter existing schema)
hsts deprecated The "includeSubdomains" parameter is deprecated. Use "includeSubDomains" (with a capital D) instead. node_modules/loopback/lib/server-app.js:74:25
Cannot migrate database schema TypeError: app.migrateSchema is not a function
    at migrate (/var/www/loopback-projects/lb4-app/dist/migrate.js:9:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
. . . 
npm ERR! Exit status 1
```

## Expected Behavior
app.migrateSchema is added to app and produces no error?

linux x64 12.13.0
├── @loopback/boot@1.5.10
├── @loopback/booter-lb3app@1.3.4
├── @loopback/context@1.23.4
├── @loopback/core@1.10.6
├── @loopback/openapi-v3@1.10.0
├── @loopback/rest@1.22.0
└── @loopback/rest-explorer@1.4.3

**Comment by CNSKnight** [comment]
@nore Ensure one's servers/server.js is not mangling app composition.
