### ISSUE TITLE
Unable to add multiple "hasOne" relations in loopback 4 with MongoDB

### ISSUE THREAD

**Issue by baltameme** [strongloop/loopback-next#4357]
@loopback/* dependencies:
  - @loopback/authentication: ^3.2.4
  - @loopback/boot: ^1.6.0
  - @loopback/build: ^3.0.0
  - @loopback/context: ^1.25.0
  - @loopback/core: ^1.12.0
  - @loopback/metadata: ^1.3.9
  - @loopback/openapi-spec-builder: ^1.2.20
  - @loopback/openapi-v3: ^1.10.3
  - @loopback/repository-json-schema: ^1.11.3
  - @loopback/repository: ^1.16.0
  - @loopback/rest: ^1.25.0
  - @loopback/testlab: ^1.10.0
  - @loopback/docs: ^2.7.0
  - @loopback/service-proxy: ^1.3.13
  - @loopback/http-caching-proxy: ^1.2.3
  - @loopback/http-server: ^1.5.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.4.6
  - @loopback/eslint-config: ^5.0.0
  - @loopback/repository-tests: ^0.8.0
  - @loopback/extension-health: ^0.2.13
  - @loopback/authorization: ^0.4.6
  - @loopback/rest-crud: ^0.6.2
  - @loopback/security: ^0.1.9
  - @loopback/authentication-passport: ^1.0.6
  - @loopback/extension-metrics: ^0.1.2

## Steps to reproduce

I am trying to build a user management App using Loopback 4 and MongoDB, where the "User" model has two "One To One" relations with two collections "UserCredentials" & "UserAccessToken".
Initially i have created the first "hasOne" relation with the collection "UserCredentials", it worked perfectly, and i was able create and insert data as expected. However, after adding the second "hasOne" the App started crashing with the same log on below:

Unhandled error in POST /user/signup: 500 TypeError: Cannot read property 'type' of undefined
    at Object.resolveHasOneMetadata (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/repository/src/relations/has-one/has-one.helpers.ts:33:21)
    at Object.createHasOneRepositoryFactory (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/repository/src/relations/has-one/has-one-repository.factory.ts:52:16)
    at UserRepository.createHasOneRepositoryFactoryFor (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/repository/src/repositories/legacy-juggler-bridge.ts:335:12)
    at new UserRepository (/Developer/NodeJS/360-teleporter-api-management-beta/src/repositories/user.repository.ts:44:33)
    at /Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/resolver.ts:73:14
    at Object.transformValueOrPromise (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/value-promise.ts:270:12)
    at Object.instantiateClass (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/resolver.ts:66:35)
    at /Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/binding.ts:533:29
    at Binding._getValue (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/binding.ts:410:14)
    at /Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/binding.ts:305:23
    at /Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/resolution-session.ts:114:13
    at Object.tryWithFinally (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/value-promise.ts:196:14)
    at Function.runWithBinding (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/resolution-session.ts:113:12)
    at Binding.getValue (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/binding.ts:302:40)
    at RequestContext.getValueOrPromise (/Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/context.ts:956:32)
    at /Developer/NodeJS/360-teleporter-api-management-beta/node_modules/@loopback/context/src/resolver.ts:155:20

-- When I traced it, i noticed that the App is crashing on the following line code inside the UserRepository: 

this.userAccessToken = this.createHasOneRepositoryFactoryFor(
      'userAccessToken',
      userAccessTokenRepositoryGetter,
    );

- This line of code is responsible for creating "hasOne" relation to the "UserAccessToken".

- After that i have tried to create another empty model and follow the same steps, and the issue is still appearing. This is the empty model. Both "UserCredentials" & "UserAccessToken" share this basic structure for identifying model ids but have different properties.

@model({
  settings: {
    strictObjectIDCoercion: true,
  },
})
export class Empty extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: false,
  })
  id?: string;

   // This is acting as a foreign key for the "User" model 
  @property({
    type: 'string',
    mongodb: {dataType: 'ObjectID'},
  })
  userId: string;

  constructor(data?: Partial<Empty>) {
    super(data);
  }
}

export interface EmptyRelations {
  // describe navigational properties here
}

export type EmptyWithRelations = Empty & EmptyRelations;

**Comment by agnes512** [comment]
@baltameme could you post your User repositories? thanks.

**Comment by baltameme** [comment]
Hi @agnes512,
Sure, you can find an archive in the attached link for all repos files.

[repositories.zip](https://github.com/strongloop/loopback-next/files/4020449/repositories.zip)

**Comment by baltameme** [comment]
Hi @agnes512, kindly any updates regarding the issue? 
Also, is there any alternative way to implement the hasOne relation with MongoDB... apparently, there is a problem with Mongo Connector with Loopback4

**Comment by agnes512** [comment]
@baltameme I couldn't reproduce the issue on my end.  My `Customer` has one `Order` and one `Review`:
#### Customer.model:
```ts
import {Entity, model, property, hasOne} from '@loopback/repository';
import {Order, Review} from '.';

@model({
  settings: {
    strictObjectIDCoercion: true,
  },
})
export class Customer extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  id?: string;

  @property({
    type: 'string',
  })
  name?: string;

  @hasOne(() => Order)
  order: Order;

  @hasOne(() => Review)
  review: Review;

  constructor(data?: Partial<Customer>) {
    super(data);
  }
}
...
```
####  Order.model
```ts
import {Entity, model, property} from '@loopback/repository';

@model({
  settings: {
    strictObjectIDCoercion: true,
  },
})
export class Order extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  id?: string;

  @property({
    type: 'string',
  })
  des?: string;

  @property({
    type: 'string',
    mongodb: {
      dataType: 'ObjectID',
    },
  })
  customerId: string;

  constructor(data?: Partial<Order>) {
    super(data);
  }
}
```
#### Customer.repository
```ts
import {
  DefaultCrudRepository,
  HasOneRepositoryFactory,
  repository,
} from '@loopback/repository';
import {Review, Customer, Order, CustomerRelations} from '../models';
import {TestdbDataSource} from '../datasources';
import {inject, Getter} from '@loopback/core';
import {OrderRepository, ReviewRepository} from '../repositories';

export class CustomerRepository extends DefaultCrudRepository<
  Customer,
  typeof Customer.prototype.id,
  CustomerRelations
> {
  public readonly order: HasOneRepositoryFactory<
    Order,
    typeof Customer.prototype.id
  >;
  public readonly review: HasOneRepositoryFactory<
    Review,
    typeof Customer.prototype.id
  >;
  constructor(
    @inject('datasources.testdb') dataSource: TestdbDataSource,
    @repository.getter('OrderRepository')
    orderRepositoryGetter: Getter<OrderRepository>,
    @repository.getter('ReviewRepository')
    reviewRepositoryGetter: Getter<ReviewRepository>,
  ) {
    super(Customer, dataSource);
    this.order = this.createHasOneRepositoryFactoryFor(
      'order',
      orderRepositoryGetter,
    );
    this.registerInclusionResolver('order', this.order.inclusionResolver);

    this.review = this.createHasOneRepositoryFactoryFor(
      'review',
      reviewRepositoryGetter,
    );
    this.registerInclusionResolver('review', this.review.inclusionResolver);
  }
}

```
Your repositories look correct to me. The error message `500 TypeError: Cannot read property 'type' of undefined
at Object.resolveHasOneMetadata` is vague. I don't think I am not able to spot where the problem is :( Could you check if your models/relations are defined correctly?

**Comment by dhmlau** [comment]
Closing due to inactivity.
