### ISSUE TITLE
AssertionError [ERR_ASSERTION]: *** setRootDir: Intl dir not found

### ISSUE THREAD

**Issue by bd100b** [strongloop/loopback-next#4800]
## Steps to reproduce

1. Install LoopBack 4 CLI: `npm install -g @loopback/cli`
2. Create a new project:` lb4 app`

## Current Behavior

It throws me an error:
```
assert.js:386
    throw err;
    ^

AssertionError [ERR_ASSERTION]: *** setRootDir: Intl dir not found under: C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli       
    at Object.setRootDir (C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli\node_modules\strong-globalize\lib\helper.js:80:5)     
    at Function.SetRootDir (C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli\node_modules\strong-globalize\lib\strong-globalize.js:63:19)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli\lib\globalize.js:11:4)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli\lib\base-generator.js:16:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

## Expected Behavior

A new project creating process should get started

## Additional information

My system:
Windows 10
NodeJS v13.10.1
npm 6.13.7

**Comment by dhmlau** [comment]
@bd100b, thanks for reporting this issue. We've published `@loopback/cli@2.0.1` to fix this problem. Could you please give it a try? Thanks!

**Comment by dhmlau** [comment]
Fixed in https://github.com/strongloop/loopback-next/pull/4799.

**Comment by bd100b** [comment]
@dhmlau now it throws me another error:

```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli\bin\cli-main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@loopback\cli\bin\cli-main.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\@loopback\\cli\\bin\\cli-main.js'
  ]
}
```

**Comment by bd100b** [comment]
@dhmlau Sory, my bad. I've uninstalled @loopback/cli and then installed it again like: `npm install -g @loopback/cli@2.0.1`, reopened my IDE and run `lb4 app` and now it works. Thanks for the fix.

**Comment by dhmlau** [comment]
I will close this issue as resolved. Thanks!
