### ISSUE TITLE
this.modelClass.create is not a function

### ISSUE THREAD

**Issue by stephaneerard** [strongloop/loopback-next#4900]
I have used lb4 cli to generate app, model, controller; repository, interactively.

## Steps to reproduce
```
lb4 model MyModel
lb4 datasource MyDataSource
lb4 repository MyModelRepository
lb4 controller MyModelController
```
Generated Model :

```
import {Entity, model, property} from '@loopback/repository';

@model()
export class Subsidiary extends Entity {
  @property({
    type: 'string',
    id: true,
    generated: true,
  })
  id?: string;

  @property({
    type: 'string',
    required: true,
  })
  isocode: string;

  @property({
    type: 'string',
    required: true,
  })
  languageIsocode: string;

  @property({
    type: 'string',
    required: true,
  })
  name: string;


  constructor(data?: Partial<Subsidiary>) {
    super(data);
  }
}

export interface SubsidiaryRelations {
  // describe navigational properties here
}

export type SubsidiaryWithRelations = Subsidiary & SubsidiaryRelations;
 
```

Generated Controller :
```
import {
  Count,
  CountSchema,
  Filter,
  FilterExcludingWhere,
  repository,
  Where,
} from '@loopback/repository';
import {
  post,
  param,
  get,
  getFilterSchemaFor,
  getModelSchemaRef,
  getWhereSchemaFor,
  patch,
  put,
  del,
  requestBody,
} from '@loopback/rest';
import {Subsidiary} from '../models';
import {SubsidiaryRepository} from '../repositories';

export class SubsidiaryController {
  constructor(
    @repository(SubsidiaryRepository)
    public subsidiaryRepository : SubsidiaryRepository,
  ) {}

  @post('/subsidiaries', {
    responses: {
      '200': {
        description: 'Subsidiary model instance',
        content: {'application/json': {schema: getModelSchemaRef(Subsidiary)}},
      },
    },
  })
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Subsidiary, {
            title: 'NewSubsidiary',
            exclude: ['id'],
          }),
        },
      },
    })
    subsidiary: Omit<Subsidiary, 'id'>,
  ): Promise<Subsidiary> {
    return this.subsidiaryRepository.create(subsidiary);
  }

  @get('/subsidiaries/count', {
    responses: {
      '200': {
        description: 'Subsidiary model count',
        content: {'application/json': {schema: CountSchema}},
      },
    },
  })
  async count(
    @param.where(Subsidiary) where?: Where<Subsidiary>,
  ): Promise<Count> {
    return this.subsidiaryRepository.count(where);
  }

  @get('/subsidiaries', {
    responses: {
      '200': {
        description: 'Array of Subsidiary model instances',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: getModelSchemaRef(Subsidiary, {includeRelations: true}),
            },
          },
        },
      },
    },
  })
  async find(
    @param.filter(Subsidiary) filter?: Filter<Subsidiary>,
  ): Promise<Subsidiary[]> {
    return this.subsidiaryRepository.find(filter);
  }

  @patch('/subsidiaries', {
    responses: {
      '200': {
        description: 'Subsidiary PATCH success count',
        content: {'application/json': {schema: CountSchema}},
      },
    },
  })
  async updateAll(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Subsidiary, {partial: true}),
        },
      },
    })
    subsidiary: Subsidiary,
    @param.where(Subsidiary) where?: Where<Subsidiary>,
  ): Promise<Count> {
    return this.subsidiaryRepository.updateAll(subsidiary, where);
  }

  @get('/subsidiaries/{id}', {
    responses: {
      '200': {
        description: 'Subsidiary model instance',
        content: {
          'application/json': {
            schema: getModelSchemaRef(Subsidiary, {includeRelations: true}),
          },
        },
      },
    },
  })
  async findById(
    @param.path.string('id') id: string,
    @param.filter(Subsidiary, {exclude: 'where'}) filter?: FilterExcludingWhere<Subsidiary>
  ): Promise<Subsidiary> {
    return this.subsidiaryRepository.findById(id, filter);
  }

  @patch('/subsidiaries/{id}', {
    responses: {
      '204': {
        description: 'Subsidiary PATCH success',
      },
    },
  })
  async updateById(
    @param.path.string('id') id: string,
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Subsidiary, {partial: true}),
        },
      },
    })
    subsidiary: Subsidiary,
  ): Promise<void> {
    await this.subsidiaryRepository.updateById(id, subsidiary);
  }

  @put('/subsidiaries/{id}', {
    responses: {
      '204': {
        description: 'Subsidiary PUT success',
      },
    },
  })
  async replaceById(
    @param.path.string('id') id: string,
    @requestBody() subsidiary: Subsidiary,
  ): Promise<void> {
    await this.subsidiaryRepository.replaceById(id, subsidiary);
  }

  @del('/subsidiaries/{id}', {
    responses: {
      '204': {
        description: 'Subsidiary DELETE success',
      },
    },
  })
  async deleteById(@param.path.string('id') id: string): Promise<void> {
    await this.subsidiaryRepository.deleteById(id);
  }
}

```

## Current Behavior

```
C:\Repos\HolidaysDemands\api>npm run start

> holidays-api@1.0.0 prestart C:\Repos\HolidaysDemands\api
> npm run build


> holidays-api@1.0.0 build C:\Repos\HolidaysDemands\api
> lb-tsc


> holidays-api@1.0.0 start C:\Repos\HolidaysDemands\api
> node -r source-map-support/register .

Server is running at http://[::1]:3000
Try http://[::1]:3000/ping
Unhandled error in POST /subsidiaries: 500 TypeError: this.modelClass.create is not a function
    at SubsidiaryRepository.create (C:\Repos\HolidaysDemands\api\node_modules\@loopback\repository\src\repositories\legacy-juggler-bridge.ts:359:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Expected Behavior
```
having no runtime error
```

## Additional information

```
node -e "console.log(process.platform, process.arch, process.versions.node)"
win32 x64 12.16.1
```

```
C:\Repos\HolidaysDemands>npm ls --prod --depth 0 | grep loopback


```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dougal83** [comment]
Can I ask for the generated repository?  Better yet, could you make an example public repo so we can clone and run?  Thanks.

**Comment by stephaneerard** [comment]
https://github.com/stephaneerard/loopback4-test

Hope it helps.
Thank you very much.

**Comment by stephaneerard** [comment]
https://github.com/stephaneerard/loopback4-test/blob/develop/src/repositories/subsidiary.repository.ts

**Comment by emonddr** [comment]
@stephaneerard , I will take a look. What version of loopback 4 are you using?

**Comment by stephaneerard** [comment]
I have used the CLI tool, latest as of yesterday.

```
PS C:\Users\Stephane_Erard> lb4 --version
@loopback/cli version: 2.0.1

@loopback/* dependencies:
  - @loopback/authentication: ^4.0.0
  - @loopback/boot: ^2.0.0
  - @loopback/build: ^4.0.0
  - @loopback/context: ^3.0.0
  - @loopback/core: ^2.0.0
  - @loopback/metadata: ^2.0.0
  - @loopback/openapi-spec-builder: ^2.0.0
  - @loopback/openapi-v3: ^3.0.0
  - @loopback/repository-json-schema: ^2.0.0
  - @loopback/repository: ^2.0.0
  - @loopback/rest: ^3.0.0
  - @loopback/testlab: ^2.0.0
  - @loopback/docs: ^3.0.1
  - @loopback/example-hello-world: ^2.0.0
  - @loopback/example-log-extension: ^2.0.0
  - @loopback/example-rpc-server: ^2.0.0
  - @loopback/example-todo: ^3.0.0
  - @loopback/example-soap-calculator: ^2.0.0
  - @loopback/service-proxy: ^2.0.0
  - @loopback/http-caching-proxy: ^2.0.0
  - @loopback/http-server: ^2.0.0
  - @loopback/example-todo-list: ^3.0.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^2.0.0
  - @loopback/eslint-config: ^6.0.0
  - @loopback/example-express-composition: ^2.0.0
  - @loopback/example-greeter-extension: ^2.0.0
  - @loopback/booter-lb3app: ^2.0.0
  - @loopback/example-lb3-application: ^2.0.0
  - @loopback/example-greeting-app: ^2.0.0
  - @loopback/example-context: ^2.0.0
  - @loopback/repository-tests: ^0.11.0
  - @loopback/extension-health: ^0.3.0
  - @loopback/authorization: ^0.5.0
  - @loopback/rest-crud: ^0.7.0
  - @loopback/security: ^0.2.0
  - @loopback/authentication-passport: ^2.0.0
  - @loopback/example-metrics-prometheus: ^0.2.0
  - @loopback/extension-metrics: ^0.2.0
  - @loopback/model-api-builder: ^2.0.0
  - @loopback/extension-logging: ^0.2.0
  - @loopback/example-access-control-migration: ^1.1.0
```

**Comment by dougal83** [comment]
It appears you neglected to mention that you've done further development beyond just:

```
lb4 model MyModel
lb4 datasource MyDataSource
lb4 repository MyModelRepository
lb4 controller MyModelController
```
Did you mean to use the key-value datasource?  I'm just going to create a new app and verify the cli is working as expected.

**Comment by stephaneerard** [comment]
I want to use mssql but one thing after another. For now in memory sqlite3.

**Comment by stephaneerard** [comment]
I have modified the code somewhat yes.
But not the generated parts.

**Comment by emonddr** [comment]
@stephaneerard , using latest loopback, I deleted your package-lock.json, removed your ssh entry in package.json, did npm install, and npm run build, with no problem.

**Comment by dougal83** [comment]
Maybe someone else can take a look

> @stephaneerard , using latest loopback, I deleted your package-lock.json, removed your ssh entry in package.json, did npm install, and npm run build, with no problem.

Did you test endpoint in explorer?

**Comment by dougal83** [comment]
@stephaneerard You might want to use `lb4 datasource` to change that as you see fit.  There appears to be no problem with the Loopback CLI or generated code. I've copied into vanilla generated project /w standard in-memory connector and it works as expected.

**Comment by emonddr** [comment]
> I have modified the code somewhat yes.
> But not the generated parts.

Exactly what areas of code did you modify?

**Comment by emonddr** [comment]
@stephaneerard , I will build one from scratch too. using your model.

**Comment by stephaneerard** [comment]
You can CRUD on Subsidiary ?

**Comment by stephaneerard** [comment]
I'm starting from scratch as you did.

Just noticed this, not related :

```
npm WARN deprecated openapi-schema-to-json-schema@2.2.0: This package is no longer maintained. Use @openapi-contrib/openapi-schema-to-json-schema instead.
```

**Comment by emonddr** [comment]
@stephaneerard , I used your model, but generated everything else. I used in -memory db.
with file : ./data/db.json (see Todo tutorial).
And I don't see the error .

I will try to create a different app using kv as you did.

**Comment by emonddr** [comment]
> I'm starting from scratch as you did.
> 
> Just noticed this, not related :
> 
> ```
> npm WARN deprecated openapi-schema-to-json-schema@2.2.0: This package is no longer maintained. Use @openapi-contrib/openapi-schema-to-json-schema instead.
> ```

Yeah, noticed it too. Mentioning it to team.

**Comment by emonddr** [comment]
hmm. using kv datasource and your model. Created a repo, then a controller. on build, I am seeing

```
> dom1kv@1.0.0 build /Users/dremond/Documents/PRs_LoopBack/community/model_create_prob/dom_test1/dom1kv/dom1kv
> lb-tsc

src/controllers/sub.controller.ts:51:38 - error TS2339: Property 'create' does not exist on type 'SubsidiaryRepository'.

51     return this.subsidiaryRepository.create(subsidiary);
                                        ~~~~~~

src/controllers/sub.controller.ts:65:38 - error TS2339: Property 'count' does not exist on type 'SubsidiaryRepository'.

65     return this.subsidiaryRepository.count(where);
                                        ~~~~~

src/controllers/sub.controller.ts:86:38 - error TS2339: Property 'find' does not exist on type 'SubsidiaryRepository'.

86     return this.subsidiaryRepository.find(filter);
                                        ~~~~

src/controllers/sub.controller.ts:108:38 - error TS2339: Property 'updateAll' does not exist on type 'SubsidiaryRepository'.

108     return this.subsidiaryRepository.updateAll(subsidiary, where);
                                         ~~~~~~~~~

src/controllers/sub.controller.ts:127:38 - error TS2339: Property 'findById' does not exist on type 'SubsidiaryRepository'.

127     return this.subsidiaryRepository.findById(id, filter);
                                         ~~~~~~~~

src/controllers/sub.controller.ts:148:37 - error TS2339: Property 'updateById' does not exist on type 'SubsidiaryRepository'.

148     await this.subsidiaryRepository.updateById(id, subsidiary);
                                        ~~~~~~~~~~

src/controllers/sub.controller.ts:162:37 - error TS2339: Property 'replaceById' does not exist on type 'SubsidiaryRepository'.

162     await this.subsidiaryRepository.replaceById(id, subsidiary);
                                        ~~~~~~~~~~~

src/controllers/sub.controller.ts:173:37 - error TS2339: Property 'deleteById' does not exist on type 'SubsidiaryRepository'.

173     await this.subsidiaryRepository.deleteById(id);
                                        ~~~~~~~~~~


Found 8 errors.
```

**Comment by emonddr** [comment]
@stephaneerard , as @dougal83 mentioned earlier, if you don't need to use kv datasource at the moment, you can avoid it and use in memory connector (if experimenting) or other connectors.

**Comment by stephaneerard** [comment]
So I'm using mssql and it is messing around.

legacy-juggler-bridge.ts line 359 this.model is a function Subsidiary.

**Comment by emonddr** [comment]
It looks like we don't have a rest controller for kv. Our CLI gives user a choice for Empty controller or CRUD controller for a kv repo, even though we don't currently have one. That's why the compile errors above show up. It is not currently supported. https://github.com/strongloop/loopback-next/issues/2737 .

**Comment by emonddr** [comment]
> So I'm using mssql and it is messing around.

Can you clarify?

**Comment by emonddr** [comment]
@stephaneerard , have you tried the Todo tutorial to get familiar with LoopBack 4?

**Comment by emonddr** [comment]
Are you using latest loopback-connector-mssql "3.8.0"  , there was an issue on Windows last week and a fix went out.

**Comment by stephaneerard** [comment]
"loopback-connector-mssql": "^3.8.0"
Ah.

**Comment by dougal83** [comment]
@emonddr Is there anything that can be done to enhance the error message for the KV connector in this circumstance?

**Comment by emonddr** [comment]
@dougal83 , I have opened: https://github.com/strongloop/loopback-next/issues/4909 .

**Comment by emonddr** [comment]
@stephaneerard, ca va maintenant?

**Comment by emonddr** [comment]
The original issue is addressed, so closing this issue. :)
