### ISSUE TITLE
 Key 'rest.http.response' not bound to any value when accessing a controller on index.js

### ISSUE THREAD

**Issue by Habbiton** [strongloop/loopback-next#5161]
## Current Behavior

I want to access some controller method from the index.ts file.
LB4 native project, not migrating from LB3.
The main() on index.ts:

    export async function main(
    	options: ApplicationConfig = {
    		shutdown: {
    			signals: ['SIGINT'],
    		},
    	},
    ) {
    	const app = new NewFleetmanagerApplication(options);
    	await app.boot();
    	await app.start();
    
    	const url = app.restServer.url;
    	console.log(`Server is running at ${url}`);
    
    	const externalApiController = await app.get<ExternalApiController>('controllers.ExternalApiController');
    	/* ACCESS CONTROLLER METHOD */
       
    	return app;
    }

The application.ts:

    export class NewFleetmanagerApplication extends BootMixin(ServiceMixin(RepositoryMixin(RestApplication))) {
    	constructor(options: ApplicationConfig = {}) {
    		super(options);
    
    		// Customize @loopback/rest-explorer configuration here
    		this.bind(RestExplorerBindings.CONFIG).to({
    			path: '/explorer',
    		});
    
    		this.setUpBindings();
    
    		// Bind authentication component related elements
    		this.component(AuthenticationComponent);
    		this.component(AuthorizationComponent);
    		registerAuthenticationStrategy(this, JWTAuthenticationStrategy);
    
    		// Set up the custom sequence
    		this.sequence(MySequence);
    
    		// Set up default home page
    		this.static('/', path.join(__dirname, '../public'));
    
    		this.component(RestExplorerComponent);
    
    		this.projectRoot = __dirname;
    		// Customize @loopback/boot Booter Conventions here
    		this.bootOptions = {
    			controllers: {
    				// Customize ControllerBooter Conventions here
    				dirs: ['controllers'],
    				extensions: ['.controller.js'],
    				nested: true,
    			},
    		};
    	}

I've tried accessing it through context (as stated [HERE](https://github.com/strongloop/loopback-next/issues/2699)), but it throws this error:

     Cannot start the application. Error: The key 'rest.http.response' is not bound to any value in context application
        at NewFleetmanagerApplication.getBinding (projectRoute/node_modules/@loopback/context/src/context.ts:703:11)
        at NewFleetmanagerApplication.getValueOrPromise (projectRoute/node_modules/@loopback/context/src/context.ts:767:26)
        at projectRoute/node_modules/@loopback/context/src/resolver.ts:155:20
        at projectRoute/node_modules/@loopback/context/src/resolution-session.ts:149:13
        at Object.tryWithFinally (projectRoute/node_modules/@loopback/context/src/value-promise.ts:196:14)
        at Function.runWithInjection (projectRoute/node_modules/@loopback/context/src/resolution-session.ts:148:12)
        at resolve (projectRoute/node_modules/@loopback/context/src/resolver.ts:139:38)
        at projectRoute/node_modules/@loopback/context/src/resolver.ts:241:12
        at Object.resolveList (projectRoute/node_modules/@loopback/context/src/value-promise.ts:168:28)
        at resolveInjectedArguments (projectRoute/node_modules/@loopback/context/src/resolver.ts:220:10)
        at Object.instantiateClass (projectRoute/node_modules/@loopback/context/src/resolver.ts:58:25)
        at projectRoute/node_modules/@loopback/context/src/binding.ts:578:29
        at Binding._getValue (projectRoute/node_modules/@loopback/context/src/binding.ts:454:14)
        at projectRoute/node_modules/@loopback/context/src/binding.ts:338:23
        at projectRoute/node_modules/@loopback/context/src/resolution-session.ts:114:13
        at Object.tryWithFinally (projectRoute/node_modules/@loopback/context/src/value-promise.ts:196:14)

## Expected Behavior
It shouldn't throw any exceptions and methods inside externalApiController should be callable through externalApiController.methodToBeCalled()

## Similar Issues
[#4572](https://github.com/strongloop/loopback-next/issues/4572)

## Additional information
linux x64 12.13.1
├── @loopback/authentication@3.3.3
├── @loopback/authorization@0.4.10
├── @loopback/boot@1.7.4
├── @loopback/context@2.1.1
├── @loopback/core@1.12.4
├── @loopback/openapi-v3@2.0.0
├── @loopback/repository@1.19.1
├── @loopback/rest@2.0.0
├── @loopback/rest-explorer@1.4.10
├── @loopback/service-proxy@1.3.17
├── loopback-connector-mongodb@4.2.0
├── loopback-connector-mysql@5.4.2

## Steps to reproduce
- Start a new lb4 project with _npm i -g @loopback/cli_
- Modify src/index.ts adding this line before `return app;`:

      const PingController = await app.get<PingController>('controllers.PingController');

- Throws this error:
`
Cannot start the application. Error: The key 'rest.http.request' is not bound to any value in context TestApplication-cef359f9-7995-4511-92c0-b052e96ccc1f
    at TestApplication.getBinding (projectRoute/test/node_modules/@loopback/context/src/context.ts:738:11)
    at TestApplication.getValueOrPromise (projectRoute/test/node_modules/@loopback/context/src/context.ts:802:26)
    at projectRoute/test/node_modules/@loopback/context/src/resolver.ts:155:20
    at projectRoute/test/node_modules/@loopback/context/src/resolution-session.ts:149:13
    at Object.tryWithFinally (projectRoute/test/node_modules/@loopback/context/src/value-promise.ts:196:14)
    at Function.runWithInjection (projectRoute/test/node_modules/@loopback/context/src/resolution-session.ts:148:12)
    at resolve (projectRoute/test/node_modules/@loopback/context/src/resolver.ts:139:38)
    at projectRoute/test/node_modules/@loopback/context/src/resolver.ts:241:12
    at Object.resolveList (projectRoute/test/node_modules/@loopback/context/src/value-promise.ts:168:28)
    at resolveInjectedArguments (projectRoute/test/node_modules/@loopback/context/src/resolver.ts:220:10)
    at Object.instantiateClass (projectRoute/test/node_modules/@loopback/context/src/resolver.ts:58:25)
    at projectRoute/test/node_modules/@loopback/context/src/binding.ts:578:29
    at Binding._getValue (projectRoute/test/node_modules/@loopback/context/src/binding.ts:454:14)
    at projectRoute/test/node_modules/@loopback/context/src/binding.ts:338:23
    at projectRoute/test/node_modules/@loopback/context/src/resolution-session.ts:114:13
    at Object.tryWithFinally (projectRoute/test/node_modules/@loopback/context/src/value-promise.ts:196:14)
`

**Comment by hacksparrow** [comment]
@Habbiton can you share a minimal app reproducing the problem?

**Comment by Habbiton** [comment]
> @Habbiton can you share a minimal app reproducing the problem?

I've added the 'Steps to reproduce'

**Comment by raymondfeng** [comment]
@Habbiton Some of the stacktrace is missing. Do you know what code in your application throws?

**Comment by coderade** [comment]
@raymondfeng I am having the same problem when I am trying to run my tests.

If I try to instantiate my repository with the `app.getRepository()` method, I receive the following error:

     ResolutionError: The key 'rest.http.request' is not bound to any value in context...

Because my repository has the `Request` class injected.

     constructor(@inject(RestBindings.Http.REQUEST) private req: Request) {} 

If  I comment on this dependency injection everything works fine. But there are other options? Can I bind this dependency? 
I really need to use the `RestBindings.Http.REQUEST` on my methods.
