### ISSUE TITLE
Problem with loopback cli version 2.6.0

### ISSUE THREAD

**Issue by chavitodb88** [strongloop/loopback-next#5396]
I have a working environment with loopback cli version 1.18.0, but when I upgrade to new version 2.6.0 and want to create a repository I get the following error:

(node:960) UnhandledPromiseRejectionWarning: Error: Cannot load /.........../src/datasources/authentication-db.datasource.config.json: ENOENT: no such file or directory, open '/.........../src/datasources/authentication-db.datasource.config.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at readDataSourceConfigFromJSON (/usr/local/lib/node_modules/@loopback/cli/lib/utils.js:641:26)
    at Object.getDataSourceConfig (/usr/local/lib/node_modules/@loopback/cli/lib/utils.js:612:5)
    at Object.exports.isConnectorOfType (/usr/local/lib/node_modules/@loopback/cli/lib/utils.js:583:26)
    at /usr/local/lib/node_modules/@loopback/cli/generators/repository/index.js:264:28
    at Array.filter (<anonymous>)
    at RepositoryGenerator.promptDataSourceName (/usr/local/lib/node_modules/@loopback/cli/generators/repository/index.js:263:50)
(node:960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dougal83** [comment]
Quite the version jump, have you checked the changelogs for the packages that have been updated?  E.g.: CLI updates can be found here: https://github.com/strongloop/loopback-next/blob/master/packages/cli/CHANGELOG.md

I can see that there is a breaking change that drops support node v8 in this package but if that is not your issue perhaps look over the other changelogs for breaking changes.  Sorry I can't point you in the right direction other than this basic guideline.

**Comment by achrinza** [comment]
Hi @chavitodb88, have you tried @dougal83's suggestion?

**Comment by dhmlau** [comment]
Closing due to inactivity. @chavitodb88, if you still encounter this problem after the above suggestion, please ping here or open a new issue. Thanks.
