### ISSUE TITLE
npm run migrate : cannot migrate models not attached to this datasource, while having model sequencing in migrate.ts 

### ISSUE THREAD

**Issue by madaky** [strongloop/loopback-next#5709]
- Visited  https://loopback.io/doc/en/lb4/todo-list-tutorial-sqldb.html - #link1
-Visited https://loopback.io/doc/en/lb4/MySQL-connector.html - #link2

## Steps to reproduce

1. Intstall @loopback/authentication  @loopback/authentication-jwt extensions

1. Suppose you are using Relational database, using the constraints as foreign keys, so you to sequence the model  in migrate.ts as guided on  #link1 above like
`models:[...model, ...relatedmodel]`
**Note if you dont have key constraints  and this model sequencing, it work fine. no error

1. Then bind the authentication-jwt datasource in to your application.ts
`this.datasource(YourDbDatasource, UserServiceBindings.DATASOURCE_NAME)`

1. when you run migrate.
`
>npm run clean
>npm run build
>npm run migrate
`

Error Come in action
`Cannot migrate database schema Error: Cannot migrate models not attached to this datasource:`

**Comment by madaky** [comment]
@dhmlau : IMO its not relating to @Authentication only, It is related to binding of datasource, if we have some tag related to datasource binding then please add this to it.

**Comment by rebecamurillo** [comment]
Just encountered the same issue when adding the authentication to my existing project (db migration was working properly before). 
- using PostgreSql connector
- to validate the data migration, I commented the line in application.ts, binding the db auth : this.datasource(YourDbDatasource...). Then all changes in DB where correctly done

**Comment by techseed** [comment]
@madaky  How did you fix it?

**Comment by pktippa** [comment]
@madaky @dhmlau  Is there any workaround for this bug?

**Comment by Arathy-sivan** [comment]
I am also facing the same issue, how to solve this issue???

**Comment by dhmlau** [comment]
I've tried to use the jwt extension and published a blog recently on using postgresql as the database for User model. https://mobilediana.medium.com/using-postgresql-with-loopback4-jwt-authentication-extension-d956ac707746. 

If you have a link to a repo that would reproduce this migration problem, please share here and we can take a look. Thanks.

**Comment by oom-** [comment]
Got the same issue since I added "name" in the model. Without it it was working but the table was created with Uppercase letter at first char.
```dart
@model({
  name: 'queue',
  settings: {
    foreignKeys: {
      fk_status_statusId: {
        name: 'fk_status_statusId',
        entity: 'Status',
        entityKey: 'id',
        foreignKey: 'statusId',
      },
      fk_logs_logsId: {
        name: 'fk_logs_logsId',
        entity: 'Logs',
        entityKey: 'id',
        foreignKey: 'logsId',
      },
      fk_source_sourceId: {
        name: 'fk_source_sourceId',
        entity: 'Source',
        entityKey: 'id',
        foreignKey: 'sourceId',
      },
    },
  },
})
```

**Comment by saunish** [comment]
I am facing the same issue, is there any workaround for this issue?

**Comment by sabulous** [comment]
> I've tried to use the jwt extension and published a blog recently on using postgresql as the database for User model. https://mobilediana.medium.com/using-postgresql-with-loopback4-jwt-authentication-extension-d956ac707746.
> 
> If you have a link to a repo that would reproduce this migration problem, please share here and we can take a look. Thanks.

I created the tables using above article and added the following lines at the end of `application.ts`

```
// Bind datasources
this.dataSource(PostgresDataSource, 'postgres'); // the datasource of the models I created
this.dataSource(PostgresDataSource, 'jwtdb'); // the datasource for User auth, as stated in LB 4 documentation
```

Then it worked. Hope this helps.

**Comment by 8vio** [comment]
Hi, I'm also with the same issue, I just have a PostgreSQL connector and some models, but when a install a new MongoDB connector. The `migrateSchema` returns:

**Comment by A-Corregidor** [comment]
Hi, same issue here. MySQL / MongoDB connectors, can't migrate any of them

Don't know what changed, everything was working OK some months ago.
I don't have the binding line `this.dataSource(MySqlSource, 'mySqlDb');` on `application.ts`, instead, I've injected it on every repository's constructor, like this: 
`
constructor(
@inject('datasources.mySqlDb') dataSource: MySqlDbDataSource,

// Other stuff
)
`

**Comment by Habbiton** [comment]
Any news/tips/comments? We're unable to migrate (ie: update DB structure)

**Comment by santomegonzalo** [comment]
I had the same problem. I found that what I was missing was the **REPOSITORY** that connects the Model with the Datasource.

```
lb4 repository
```
and then you can select the DataSource and the Models that you want to connect with it.

**Comment by ashelman-ec** [comment]
Hit this error too. Similar to @madaky I had the Todo example (extended with TodoList) running with MySQL with no problems. Then followed the [JWT Authentication](https://loopback.io/doc/en/lb4/Authentication-tutorial.html) tutorial to try to add authentication.

Trying to migrate the database returns the error:

```
Migrating schemas (alter existing schema)
Cannot migrate database schema Error: Cannot migrate models not attached to this datasource: TodoList Todo User
    at C:\...\todo-list\node_modules\loopback-datasource-juggler\lib\datasource.js:1146:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Without DB migration the app will run, but trying POST /signup to the UserController returns a 500 statusCode and the terminal console logs error that User table does not exist:
```
WARNING: relational database doesn't support {strict: false} mode. {strict: true} mode will be set for model User instead.
Request POST /signup failed with status code 500. Error: ER_NO_SUCH_TABLE: Table 'loopback_todo.User' doesn't exist
```

**Comment by ashelman-ec** [comment]
Update: tried following the blog post mentioned above by @dhmlau using Option 2.

However, still hit the same error when trying to migrate:
```
Migrating schemas (alter existing schema)
Cannot migrate database schema Error: Cannot migrate models not attached to this datasource: TodoList Todo User UserCredentials
    at C:\...\todo-list-Auth\node_modules\loopback-datasource-juggler\lib\datasource.js:1146:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by ashelman-ec** [comment]
Update: was successful with [blog post](https://mobilediana.medium.com/using-postgresql-with-loopback4-jwt-authentication-extension-d956ac707746) Option 1, which is manually adding the SQL tables to the existing database. This was painful, and not easy to maintain, but at least it works for now.

Using MySQL database , here are the SQL commands used to create the tables and the foreign key (note: change the database name from `loopback_todo` to whatever your database is named):
```
CREATE TABLE `loopback_todo`.`UserCredentials` ( `id` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , `password` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , `userId` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `loopback_todo`.`User` ( `id` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , `realm` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL , `username` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL , `email` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , `emailVerified` TINYINT(1) NULL DEFAULT NULL , `verificationToken` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL , PRIMARY KEY (`id`) USING BTREE, UNIQUE (`email`)) ENGINE = InnoDB;

ALTER TABLE `loopback_todo`.`UserCredentials` DROP INDEX `fk_userCredentials_userId`, ADD UNIQUE `fk_userCredentials_userId` (`userId`) USING BTREE;
```

**Comment by chaseoli** [comment]
I was getting a similar error when following along with the todo-list example and then tried to follow the jwt example and use mssql instead of in-memory db.  Error output look like:

```terminal
Cannot migrate database schema Error: Cannot migrate models not attached to this datasource: TodoList Todo TodoListImage
    at /home/chaseo/repos/todo-list/node_modules/loopback-datasource-juggler/lib/datasource.js:1146:12
```
but then I updated the `migrate.ts`  for the following
![image](https://user-images.githubusercontent.com/6847000/197424770-6b78fccb-8c6c-425a-b5e3-4fefb06e59d0.png)

and this fixed my error and allowed me to migrate successfully.

**Comment by adrienrn** [comment]
I had the same issue. Make sure you don't have 2 datasources under datasources/. I had 2: memory and postgresql. By running the script with a few `console.log` (I know that's debugging level 0), I got to see that the migrate script runs fine for postgresql then errors out for the memory. It makes sense since all my repositories are bound to postgresql and not memory.

On this dump, you can see it runs first for `DbDataSource.DataSource.autoupdate`, works fine. THEN runs for `MemoryDataSource.DataSource.autoupdate` where all the models are invalid.
```
$ node -r dotenv/config ./dist/migrate
Migrating schemas (alter existing schema)
[
  'Attendance',
  'Event',
  'RoomAccessDecision',
  'RoomAccess',
  'RoomAttendance',
  'RoomGroup',
  'Room',
  'User',
  'VenueSpace',
  'Venue'
]
Error
    at DbDataSource.DataSource.autoupdate (/Users/adrien/Documents/personel/eva/eva-rest/node_modules/loopback-datasource-juggler/lib/datasource.js:1135:11)
    at EvaRestApplication.migrateSchema (/Users/adrien/Documents/personel/eva/eva-rest/node_modules/@loopback/repository/dist/mixins/repository.mixin.js:249:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async migrate (/Users/adrien/Documents/personel/eva/eva-rest/dist/migrate.js:10:5)
Attendance true
RoomAccessDecision true
RoomGroup true
User true
Venue true
Room true
RoomAccess true
RoomAttendance true
VenueSpace true
Event true
...
[]
Error
    at MemoryDataSource.DataSource.autoupdate (/Users/adrien/Documents/personel/eva/eva-rest/node_modules/loopback-datasource-juggler/lib/datasource.js:1135:11)
    at EvaRestApplication.migrateSchema (/Users/adrien/Documents/personel/eva/eva-rest/node_modules/@loopback/repository/dist/mixins/repository.mixin.js:249:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async migrate (/Users/adrien/Documents/personel/eva/eva-rest/dist/migrate.js:10:5)
Attendance false
RoomAccessDecision false
RoomGroup false
User false
Venue false
Room false
RoomAccess false
RoomAttendance false
VenueSpace false
Event false
```

**Comment by Subiramani** [comment]
I'm just wondering the fix that I've done is going to affect any other functionalities in the app. BTW, I faced the same issue after integrating the jwt binding

```javascript
this.datasource(YourDbDatasource, UserServiceBindings.DATASOURCE_NAME)`
```

This is my original datasource called `db`
```javascript
const config = {
  name: 'db',
  connector: 'postgresql',
  url: '',
  host: 'localhost',
  port: 5432,
  user: 'postgres',
  password: 'password',
  database: 'mydb',
};
```

I've created another datasource named `jwtdb` as the name as the same from the built-in namespace `UserServiceBindings` like below and removed the binding syntax from the `application.ts`.
```javascript
const config = {
  name: 'jwtdb',
  connector: 'postgresql',
  url: '',
  host: 'localhost',
  port: 5432,
  user: 'postgres',
  password: 'password',
  database: 'mirow',
  disableMigration: true,
};
```
Note: The above fix doesn't affected any of the CRUD or Auth actions I do in the app so far.
Questions:
1. Is it fine to have this fix?
2. Does the removal of binding line from application.ts have anything to do with it?
3. If I add this in the application.ts that also working fine. is it wrong?
```javascript
this.datasource(YourDbDatasource, UserServiceBindings.DATASOURCE_NAME)`
```


I'm still grinding through the node_modules and loopback code to find anything breaks. I hope you guys understand. Thanks.

**Comment by thecoolestcoderrushil** [comment]
npm run migrate failing with cannot migrate models not attached to this datasource is a painful bug, since adding the authentication-jwt extension with a second datasource breaks schema migration even though the models work fine, and many users hit the same error across postgres, mysql, and mongodb with one reporter getting 11 upvotes. rehearsing the migration on a production-shaped twin first would surface the datasource problem before deploy day. antifailure.dev (https://antifailure.dev) builds disposable database twins for migration rehearsal and is open source and free to try, with demos available for teams that want one.
