### ISSUE TITLE
save method throws error "this.definition.idName is not a function"

### ISSUE THREAD

**Issue by frbuceta** [strongloop/loopback-next#5812]
## Steps to reproduce

Calling the `save` method of the repository already gives this error. `this.repository.save(entity)`

## Current Behavior

You try to send a request and it already breaks

```
Unhandled error in POST /working-days/add-revision?workingDayId=17454: 500 TypeError: this.definition.idName is not a function
    at Function.getIdOf (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/repository/src/model.ts:333:36)
    at DayCheckRepository.save (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/repository/src/repositories/legacy-juggler-bridge.ts:379:33)
    at WorkingDayController.saveOrReplace (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/src/controllers/working-day.controller.ts:111:36)
    at invokeTargetMethod (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/invocation.ts:255:47)
    at /Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/invocation.ts:232:12
    at Object.transformValueOrPromise (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/value-promise.ts:298:12)
    at invokeTargetMethodWithInjection (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/invocation.ts:227:10)
    at InterceptedInvocationContext.invokeTargetMethod (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/invocation.ts:118:14)
    at targetMethodInvoker (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor.ts:349:23)
    at /Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor-chain.ts:218:14
    at Object.transformValueOrPromise (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/value-promise.ts:298:12)
    at GenericInterceptorChain.invokeNextInterceptor (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor-chain.ts:213:12)
    at GenericInterceptorChain.next (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor-chain.ts:201:17)
    at GenericInterceptorChain.invokeInterceptors (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor-chain.ts:178:17)
    at Object.invokeInterceptors (/Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor-chain.ts:250:16)
    at /Users/fran/Projects/xxxxxxx/xxxx/xxxxxx-monitor-api/node_modules/@loopback/context/src/interceptor.ts:351:14
```

## Expected Behavior

You should modify or create a record in the database without giving this error

## Additional information

```
➜  xxxxxx-monitor-api git:(master) ✗   node -e 'console.log(process.platform, process.arch, process.versions.node)'
  darwin x64 14.4.0
➜  xxxxxx-monitor-api git:(master) ✗   npm ls --prod --depth 0 | grep loopback
├── @loopback/authentication@4.2.7
├── @loopback/boot@2.3.3
├── @loopback/context@3.9.0
├── @loopback/core@2.8.0
├── @loopback/openapi-v3@3.4.3
├── @loopback/repository@2.7.0
├── @loopback/rest@5.1.1
├── @loopback/rest-explorer@2.2.4
├── @loopback/service-proxy@2.3.2
├── loopback-connector-mssql@3.8.0
➜  xxxxxx-monitor-api git:(master) ✗
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by jannyHou** [comment]
Reproduced by adding controller method

```ts
@put('/todos/save/{id}', {
    responses: {
      '204': {
        description: 'Todo save PUT success',
      },
    },
  })
  async saveTodo(
    @requestBody() todo: Todo,
  ): Promise<void> {
    await this.todoRepository.save(todo);
  }
```

**Comment by jannyHou** [comment]
It's caused by this function `getIdOf`

https://github.com/strongloop/loopback-next/blob/4f9584cfd89814a8c16511d57c1fff6ae5ff41ab/packages/repository/src/repositories/legacy-juggler-bridge.ts#L379

Should fix it and add tests for it.

**Comment by bajtos** [comment]
I think the problem is inside `getIdOf`:

https://github.com/strongloop/loopback-next/blob/08eeab8b716da6296434392888cba92d9d106286/packages/repository/src/model.ts#L435-L436

The class `ModelDefinition` does not provide any `idName()` function. It provides `idProperties()` instead. I am proposing to rework `getIdOf` as follows, using `Entity`'s static method `getIdProperties`.

```js
const idName = this.getIdProperties()[0];
return entityOrData[idName];
```

It would be great to add some unit tests executing `getIdOf` with this scenario.
