### ISSUE TITLE
Error in embedded models for nested properties

### ISSUE THREAD

**Issue by alexnfsc175** [strongloop/loopback-next#6150]
## Steps to reproduce

```ts
@model()
class Category {
  @property({ type: 'number', id: true, required: true, generated: true, })
  id: number;
  @property()
  name: string;
}

@model()
class Product {
  @property({ type: 'number', id: true, required: true, generated: true, })
  id: number;
  @property({required: true})
  name: string;
  @property()
  category: Category;
}

/// Controller

export class ProductController {
  constructor(
    @repository(ProductRepository)
    public productRepository: ProductRepository,
  ) { }

  @post('/products')
  async create(
    @requestBody({
      content: {
        'application/json':
        {
          schema: getModelSchemaRef(Product, { title: "Productchema" })
        }
      }
    })
    product: Omit<Product, 'id'>,
  ): Promise<Product> {
    return this.productRepository.create(product);
  }
}
```

The following error occurs:
```sh
Cannot start the application. Error: Property Product.category does not have "type" in its definition
    at modelToJsonSchema (C:\Users\AlexPereira\Documents\dev\mk-backend-dev-server\services\tenants\node_modules\@loopback\repository-json-schema\dist\build-schema.js:344:19)
    at getJsonSchema (C:\Users\AlexPereira\Documents\dev\mk-backend-dev-server\services\tenants\node_modules\@loopback\repository-json-schema\dist\build-schema.js:44:18)

```

this exception is thrown by this line: 

https://github.com/strongloop/loopback-next/blob/1677195321ce06a1d7467233979ca4f321870e40/packages/repository-json-schema/src/build-schema.ts#L473

so I changed it to that

```ts
@model()
class Product {
  @property({ type: 'number', id: true, required: true, generated: true, })
  id: number;
  @property({required: true})
  name: string;
  @property({type: Category})
  category: Category;
}
```
but the error continues, I am using the latest version of the loopback packages

```json
{
  "dependencies": {
    "@loopback/boot": "^2.4.1",
    "@loopback/context": "^3.9.4",
    "@loopback/core": "^2.9.3",
    "@loopback/openapi-v3": "^3.4.7",
    "@loopback/repository": "^2.11.0",
    "@loopback/rest": "^6.0.0",
    "@loopback/rest-explorer": "^2.2.8",
    "@loopback/service-proxy": "^2.3.6",
    "@types/socket.io-client": "^1.4.32",
    "db-migrate": "^0.11.11",
    "db-migrate-pg": "^1.0.0",
    "lb4-utils": "0.0.7",
    "lodash": "^4.17.19",
    "loopback-connector-postgresql": "^3.8.0",
    "loopback-rabbitmq": "^1.0.4",
    "socket.io-client": "^2.3.0",
    "socket.io-emitter": "^3.1.1",
    "tsc-watch": "^4.0.0",
    "uuid": "^3.4.0"
  },
  "devDependencies": {
    "@loopback/build": "^6.2.0",
    "@loopback/eslint-config": "^9.0.0",
    "@loopback/testlab": "^3.2.2",
    "@types/lodash": "^4.14.156",
    "@types/node": "^10.17.28",
    "@types/uuid": "^3.4.7",
    "@typescript-eslint/eslint-plugin": "^2.31.0",
    "@typescript-eslint/parser": "^2.31.0",
    "eslint": "^7.6.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-eslint-plugin": "^2.2.1",
    "eslint-plugin-mocha": "^7.0.0",
    "source-map-support": "^0.5.19",
    "typescript": "~3.9.7"
  }
}

```

**Comment by alexnfsc175** [comment]
The error was caused by automatic import from index.ts
```ts
import { Product } from '.';
```
but when the import comes from the product.model.ts file the error doesn't happen

```ts
import { Product } from './product.model';
```
