### ISSUE TITLE
Unexpected token export after running "node -r source-map-support/register ." on start script

### ISSUE THREAD

**Issue by cal3432** [strongloop/loopback-next#6448]
## Steps to reproduce

Create a new lb4 app.
run npm start

## Current Behavior

```
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1050:16)
    at Module._compile (internal/modules/cjs/loader.js:1098:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\coding\multiplayer\node_modules\@loopback\context\src\value-promise.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

## Expected Behavior

The app to start at localhost:3000

## Link to reproduction sandbox

Reproduction sandbox doesn't catch the bug for some reason.

## Additional information

node: win32 x64 13.3.0

+-- @loopback/boot@3.0.1
+-- @loopback/core@2.10.1
+-- @loopback/repository@3.0.1
+-- @loopback/rest@7.0.1
+-- @loopback/rest-explorer@3.0.1
+-- @loopback/service-proxy@3.0.1
`-- tslib@2.0.1

**Comment by achrinza** [comment]
Please try the following:

1. Use a supported version of Node.js (10, 12, 14). v13 has reached EOL.
2. Clean the build files:
   ```
   npm run clean
   npm ci
   npm start
   ```

**Comment by cal3432** [comment]
I was running on v13, thats the problem.
