### ISSUE TITLE
Sequence throws error when controller functions return booleans

### ISSUE THREAD

**Issue by kjdelisle** [strongloop/loopback-next#667]
# Description/Steps to reproduce
When attempting to return a boolean value from a controller function, an unhandled error occurs, similar to the sample below:

```
Unhandled error in PATCH /todo/1/items/3: 500 TypeError: First argument must be a string or Buffer
    at write_ (_http_outgoing.js:640:11)
    at ServerResponse.write (_http_outgoing.js:615:10)
    at DefaultSequence.writeResultToResponse [as send] (/Users/kevin/dev/loopback/next-examples/loopback4-example-getting-started/node_modules/@loopback/rest/lib/writer.js:30:18)
    at DefaultSequence.handle (/Users/kevin/dev/loopback/next-examples/loopback4-example-getting-started/node_modules/@loopback/rest/lib/sequence.js:79:18)
    at <anonymous>
```
- Make your function return a boolean
- Call the route bound to that controller and function
- Observe the internally logged error
- The external-facing status will report 200 OK

# Expected result
If this is a result of not providing some OpenAPI spec information regarding return type and format, then this should throw a more descriptive error message to that effect.

If it's meant to be auto-coerced, then it's currently not doing so.

**Comment by kjdelisle** [comment]
Tested this with latest release and the issue is no longer present.
