### ISSUE TITLE
@loopback/context - debug.destroy is deprecated

### ISSUE THREAD

**Issue by evantrimboli** [strongloop/loopback-next#6835]
## Steps to reproduce

Run the ping controller endpoint from the default package creation.

## Current Behavior

(node:33604) DeprecationWarning: Instance method `debug.destroy()` is deprecated and no longer does anything. It will be removed in the next major version of `debug`.

## Expected Behavior

No warning

## Additional information

```
DeprecationWarning: Instance method `debug.destroy()` is deprecated and no longer does anything. It will be removed in the next major version of `debug`.
    at InterceptedInvocationContext.close (D:\git\foo\lb\node_modules\@loopback\context\src\context.ts:432:17)
    at D:\git\foo\lb\node_modules\@loopback\context\src\interceptor.ts:353:25
    at resolve (D:\git\foo\lb\node_modules\@loopback\context\src\value-promise.ts:236:7)
    at tryCatchFinally (D:\git\foo\lb\node_modules\@loopback\context\src\value-promise.ts:230:10)
    at Object.tryWithFinally (D:\git\foo\lb\node_modules\@loopback\context\src\value-promise.ts:197:10)
    at Object.invokeMethodWithInterceptors (D:\git\foo\lb\node_modules\@loopback\context\src\interceptor.ts:345:10)
    at Object.invokeMethod (D:\git\foo\lb\node_modules\@loopback\context\src\invocation.ts:191:10)
    at ControllerRoute.invokeHandler (D:\git\foo\lb\node_modules\@loopback\rest\src\router\controller-route.ts:145:12)
    at D:\git\foo\lb\node_modules\@loopback\rest\src\providers\invoke-method.provider.ts:51:24
    at D:\git\foo\lb\node_modules\@loopback\express\src\middleware-interceptor.ts:131:19
    at D:\git\foo\lb\node_modules\@loopback\express\src\middleware-interceptor.ts:131:19
    at D:\git\foo\lb\node_modules\@loopback\rest\src\providers\send.provider.ts:46:24
    at MiddlewareSequence.handle (D:\git\foo\lb\node_modules\@loopback\rest\src\sequence.ts:291:5)
    at HttpHandler._handleRequest (D:\git\foo\lb\node_modules\@loopback\rest\src\http-handler.ts:115:5)
```

The issue with the memory leak seems to have been resolved in the underlying library here:

https://github.com/visionmedia/debug/commit/72e7f864bd75fc8353e4dd450de96d9104ba9f35
https://github.com/visionmedia/debug/commit/e2d3bc9e428bdd45adb8d6e7f8ab543bee54d9a6

## Related Issues

The change seems like it was introduced here: https://github.com/strongloop/loopback-next/issues/5943

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-next/pull/6811
