### ISSUE TITLE
500 ResolutionError: The key 'security.user' is not bound to any value

### ISSUE THREAD

**Issue by naveeng2228** [strongloop/loopback-next#7079]
Hello Everyone,

I'm having the following issue since couple of weeks. I've tried all possible ways but no luck.

**Code:**
```
import {authenticate} from '@loopback/authentication';
import {repository} from '@loopback/repository';
import {get} from '@loopback/rest';
import {TblSellerProductMasterRepository} from '../repositories';

@authenticate.skip()
export class StoreFrontController {
  constructor(
    @repository(TblSellerProductMasterRepository)
    public productsMasterRepo: TblSellerProductMasterRepository
  ){}

  @get("/sf/products")
  async getSFProducts(): Promise<object> {
    return {};
  }
}

```

**Error Log:**
```
Unhandled error in GET /sf/products: 500 ResolutionError: The key 'security.user' is not bound to any value in context InterceptedInvocationContext-cR-VBcMLTZient5J4gh2pg-19 (context: InterceptedInvocationContext-cR-VBcMLTZient5J4gh2pg-19, binding: security.user, resolutionPath: @StoreFrontController.prototype.products[0])
    at InterceptedInvocationContext.getValueOrPromise (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\context.ts:810:13)
    at PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\resolver.ts:159:20
    at PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\resolution-session.ts:157:13
    at tryCatchFinally (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\value-promise.ts:222:14)     
    at Object.tryWithFinally (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\value-promise.ts:197:10)
    at Function.runWithInjection (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\resolution-session.ts:156:12)
    at resolve (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\resolver.ts:143:38)
    at PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\resolver.ts:246:12
    at Object.resolveList (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\value-promise.ts:169:28)  
    at Object.resolveInjectedArguments (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\resolver.ts:224:10)
    at invokeTargetMethodWithInjection (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\invocation.ts:223:25)
    at InterceptedInvocationContext.invokeTargetMethod (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\invocation.ts:119:14)
    at targetMethodInvoker (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\interceptor.ts:349:23)   
    at PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\interceptor-chain.ts:218:14
    at Object.transformValueOrPromise (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\value-promise.ts:298:12)
    at GenericInterceptorChain.invokeNextInterceptor (PROJECT_URL\lb4_web_services\node_modules\@loopback\context\src\interceptor-chain.ts:213:12)
```

Your help is highly appreciated. 
Thanks in advance.

**Comment by achrinza** [comment]
Closing due to inactivity.

**Comment by sudheersuri** [comment]
I haved injected user object in constructor yet am receiving this issue 
```

constructor(
    @inject(TokenServiceBindings.TOKEN_SERVICE)
    public jwtService: TokenService,
    @inject(UserServiceBindings.USER_SERVICE)
    public userService: AuthUserService,
    @inject(SecurityBindings.USER, {optional: true})
    public user: UserProfile,
    @repository(UserRepository) 
    protected userRepository: UserRepository,
  ) {}
```

**Comment by moizaltaf53** [comment]
I am also getting the same error fellas!
is there any end to the world of errors
