### ISSUE TITLE
Prompt issue by creating model with "base" argument

### ISSUE THREAD

**Issue by canmustu** [strongloop/loopback-next#7365]
## Steps to reproduce

I specified an option ( `base` ) to create model not to prompt me the question but It still prompts me for `base`.
I tried this option by passing config file and other way which is `--base entity` way but same behaviour.

My `config.json`
```
{
  "base": "entity"
}
```

My controller creation `CLI command`:

```
lb4 model test --config config.json
```

## Current Behavior

Prompt me to choose a base:

```
? Please select the model base class (Use arrow keys)
❯ Entity (A persisted model with an ID) 
  Model (A business domain object) 
  ----- Custom Models -----
  Test 
```

## Expected Behavior

Not to prompt me about specified base.

**Comment by dhmlau** [comment]
@canmustu, I believe it's `Entity` instead of `entity`. 
I tried with the following and the first prompt is asking about additional properties. 
```
{
  "base": "Entity"
}
```

Hope it helps.

**Comment by canmustu** [comment]
@dhmlau `base` value is working now. Thanks for this but there is another problem while creating a model 😞 

You write me on my another issue to create a model with example config below:

```
{
  "name": "Customer",
  "base": "Entity",
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "required": false
    },
    "name": {
      "type": "string",
      "length": 200,
      "id": false,
      "required": true
    }
  }
}
```

When I try to create model with this config:

**CLI:**

`lb4 model --config config.json --yes`

**Result:**

```
Model Customer will be created in src/models/customer.model.ts

Let's add a property to Customer
Enter an empty property name when done

? Enter the property name: 
```

Still prompts me a property name to create a property for this model but I don't want another property. I specify all my properties in the config. However, It throws an error when I just enter it or passing a property name: 

```
(node:74396) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Environment'
    |     property '_rootGenerator' -> object with constructor 'ModelGenerator'
    |     property 'options' -> object with constructor 'Object'
    --- property 'env' closes the circle
    at JSON.stringify (<anonymous>)
    at ModelGenerator.promptPropertyName (/usr/local/lib/node_modules/@loopback/cli/generators/model/index.js:375:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:74396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dhmlau** [comment]
Closing as resolved.
