### ISSUE TITLE
Can't run test in a package on a clean copy of loopback-next

### ISSUE THREAD

**Issue by virkt25** [strongloop/loopback-next#978]
# Description/Steps to reproduce

```
git clone https://github.com/strongloop/loopback-next.git
cd loopback-next
npm run bootstrap
cd packages/rest
npm t
```

Get an error message saying:
```
Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taranveer/Desktop/loopback-next/packages/context/index.js:6:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taranveer/Desktop/loopback-next/packages/rest/src/router/routing-table.ts:11:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taranveer/Desktop/loopback-next/packages/rest/src/index.ts:9:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taranveer/Desktop/loopback-next/packages/rest/index.ts:8:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taranveer/Desktop/loopback-next/packages/rest/test/unit/backward-compatibility.test.ts:6:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/taranveer/Desktop/loopback-next/packages/build/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/taranveer/Desktop/loopback-next/packages/build/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/taranveer/Desktop/loopback-next/packages/build/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/taranveer/Desktop/loopback-next/packages/build/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! Test failed.  See above for more details.
```

If after `npm run bootstrap` we run `npm t` from top-level, everything works fine! And then if you go into a package and run `npm t`, it also works fine.

# Link to reproduction sandbox

See above for repro.

# Expected result

It should've built the `rest` package and ran the tests.

# Additional information

**Comment by raymondfeng** [comment]
For individual packages, you need to run `npm run build && npm test`.

**Comment by virkt25** [comment]
The `pretest` is supposed to do the build. For some reason it fails if done in the manner stated above.

**Comment by raymondfeng** [comment]
We don't have `pretest` for individual packages.

**Comment by virkt25** [comment]
We do have a `pretest` in all individual `package.json` files for all packages with a test that require a build step.

**Comment by raymondfeng** [comment]
Yes. You are right about `pretest`. 

But the behavior you observe is still expected. In your case, you try to run `npm test` in `packages/rest`. Right after `npm run bootstrap`, the packages are connected with symbolic links so that `rest` see `@loopback/context`. But the `context` module has not been built yet. That's what the error complains.
